### ISSUE TITLE
Upgrade from 7.13 to 8.x fails due to missing .env file

### ISSUE THREAD

**Issue by vladaman** [salesagility/SuiteCRM#10018]
I followed manual on SuiteCRM site to migrate 7.13.2 to 8.2.4

I copied the files to /Suite8/public/legacy folder and when I run `./bin/console suitecrm:app:setup-legacy-migration` I get following error:

```
PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/var/www/crm/SuiteCRM-8.2.4/.env" environment file. in /var/www/crm/SuiteCRM-8.2.4/vendor/symfony/dotenv/Dotenv.php:565
Stack trace:
#0 /var/www/crm/SuiteCRM-8.2.4/vendor/symfony/dotenv/Dotenv.php(92): Symfony\Component\Dotenv\Dotenv->doLoad()
#1 /var/www/crm/SuiteCRM-8.2.4/vendor/symfony/dotenv/Dotenv.php(114): Symfony\Component\Dotenv\Dotenv->load()
#2 /var/www/crm/SuiteCRM-8.2.4/config/bootstrap.php(47): Symfony\Component\Dotenv\Dotenv->loadEnv()
#3 /var/www/crm/SuiteCRM-8.2.4/bin/console(30): require('...')
#4 {main}
  thrown in /var/www/crm./SuiteCRM-8.2.4/vendor/symfony/dotenv/Dotenv.php on line 565
```

Problem is, that my old installation doesn't have .env file. My DB config is in config.php

**Comment by vladaman** [comment]
OK I found the issue. While copying files the .env file from .zip file was not copied. It was not related to legacy but new upgrade package content.

**Comment by chris001** [comment]
> OK I found the issue. While copying files the .env file from .zip file was not copied. It was not related to legacy but new upgrade package content.

What command did you run to fix it?
