### ISSUE TITLE
yarn run build:core Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dwaltsch** [salesagility/SuiteCRM#10126]
#### Issue
When running the following command I encounter an Maximum call stack size exceeded error
````
yarn run build:core
````

#### Expected Behavior
The following commands from [here](https://docs.suitecrm.com/8.x/developer/installation-guide/front-end-installation-guide/) should execute and end up displaying the site

#### Actual Behavior
````
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'core'
------------------------------------------------------------------------------
✖ Compiling with Angular in legacy View Engine compilation mode.
Maximum call stack size exceeded
verbose 28.625965246 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/usr/share/yarn/lib/cli.js:790:113)
    at /usr/share/yarn/lib/cli.js:34406:30
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@SuiteCRM8:/var/www/html/suitev8dev# 
````

#### Your Environment`

````
root@SuiteCRM8:/var/www/html/suitev8dev# ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.0
Node: 14.20.1
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 12.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   12.2.18
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@angular/cdk                    12.2.13
@schematics/angular             12.1.0
ng-packagr                      12.2.7
rxjs                            6.6.7
typescript                      4.3.5
webpack                         5.88.2
    
root@SuiteCRM8:/var/www/html/suitev8dev# 
````

**Comment by dwaltsch** [comment]
i somehow avoided the problem changed the configuration a bit however when trying to build it new i still have the same error
````
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.18
Node: 14.15.1
Package Manager: yarn 1.22.10
OS: linux x64

Angular: 12.1.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   12.2.18
@angular-devkit/core            12.2.18
@angular-devkit/schematics      12.2.18
@angular/cdk                    12.2.13
@schematics/angular             12.2.18
ng-packagr                      12.2.7
rxjs                            6.6.7
typescript                      4.3.5
webpack                         5.88.2

`````
