### ISSUE TITLE
Can't reply to emails

### ISSUE THREAD

**Issue by Kapustlo** [salesagility/SuiteCRM#10124]
#### Issue
500 error when clicking on the "reply" button on an email page.

#### Expected Behavior
200 ok response rendering the reply page.

#### Actual Behavior
500 error. Error from logs:

```php
PHP Fatal error:  Uncaught Error: Call to a member function getAddresses() on null in /bitnami/suitecrm/vendor/javanile/php-imap2/src/Polyfill.php:73
Stack trace:
#0 /bitnami/suitecrm/vendor/javanile/php-imap2/bootstrap.php(1515): Javanile\Imap2\Polyfill::rfc822ParseHeaders()
#1 /bitnami/suitecrm/vendor/javanile/php-imap2/bootstrap.php(1521): imap_rfc822_parse_headers()
#2 /bitnami/suitecrm/include/Imap/Imap2Handler.php(874): imap2_rfc822_parse_headers()
#3 /bitnami/suitecrm/modules/InboundEmail/InboundEmail.php(5387): Imap2Handler->rfc822ParseHeaders()
#4 /bitnami/suitecrm/modules/Emails/EmailsController.php(806): InboundEmail->returnImportedEmail()
#5 /bitnami/suitecrm/modules/Emails/EmailsController.php(654): EmailsController->composeBean()
#6 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(522): EmailsController->action_ReplyTo()
#7 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(491): SugarController->do_action()
#8 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(465): SugarController->handle_action()
#9 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(361): SugarController->process()
#10 /bitnami/suitecrm/include/MVC/SugarApplication.php(101): SugarController->execute()
#11 /bitnami/suitecrm/index.php(52): SugarApplication->execute()
#12 {main}
  thrown in /bitnami/suitecrm/vendor/javanile/php-imap2/src/Polyfill.php on line 73
```

The problem seems to be in the rfc822ParseHeaders function that's in the include/Imap/Imap2Handler.php file. For some reason "From:" header that's in the $headers is missing the email address part there only containing the sender's name but the "Reply-To" email is fine. For example: From: JohnDoe Reply-To: john.doe@example.com

#### Steps to Reproduce
1. Create an inbound email account with corporate email
2. Load inbound emails
3. Reply to an email

#### Your Environment
* SuiteCRM Version used: 7.13.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): LibreWolf 107.0
* Environment name and version (e.g. MySQL, PHP 7): Docker docker.io/bitnami/suitecrm:7 image and MySQL 5.7.27-30

**Comment by pgorod** [comment]
You didn't fill in your PHP version...

Make sure it's within the Matrix: 
https://docs.suitecrm.com/admin/compatibility-matrix/

**Comment by Kapustlo** [comment]
> 

@pgorod I use the official Docker image, I'm not sure what PHP version is there. I'll try to check

**Comment by Kapustlo** [comment]
docker exec -it suitecrm php --version:

```bash
PHP 8.0.29 (cli) (built: Jul 24 2023 21:31:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.29, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.29, Copyright (c), by Zend Technologies
```

**Comment by Kapustlo** [comment]
> 

Actually after debugging a little bit more, all keys in the $ret (rfc822ParseHeaders) look fine, including the "From" header but I'm not sure where to look, so I'll give some more information if needed
