### ISSUE TITLE
Uploading Email to History with attachment, error for view attachment

### ISSUE THREAD

**Issue by GrupImatica** [salesagility/SuiteCRM#2470]
Hi, i'm getting error 500 when i go to see an uploaded file without any problems in History / Attach Email / With Attachments

After save with any error, i go to the email, and try to open file and i get error 500
#### Your Environment

- SuiteCRM Version used:7.7.6
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Any
- Environment name and version (e.g. MySQL, PHP 7): MSSQL , 
- Operating System and version (e.g Ubuntu 16.04): W.2012 R2

**Comment by shogunpol** [comment]
@GrupImatica , can you follow by template when you create an issue? So i am not able to replicate the issue, because i do not have enough information about an issue, i do not know what module, operation or functionalities you use. So: when you start, what you select, where you upload/download file. Please provide step-by-step reproducing issue section.
Thanks for your contribution.

**Comment by GrupImatica** [comment]
Hi, i go to an account: 
![acc1](https://cloud.githubusercontent.com/assets/20840700/19761725/5cdf86b8-9c37-11e6-9052-2e098b8b7cdb.PNG)

i go to history:
![acc2](https://cloud.githubusercontent.com/assets/20840700/19761743/6a59353c-9c37-11e6-8689-77bd8fe8955e.PNG)

i add new item with attachment (any PDF)
![acc3](https://cloud.githubusercontent.com/assets/20840700/19761798/a22863d4-9c37-11e6-9963-f696159e5156.PNG)

And i go to new item created:
![acc4](https://cloud.githubusercontent.com/assets/20840700/19761834/c37bafbe-9c37-11e6-9192-ad70305f7000.PNG)

When i clic to see PDF:
![acc5](https://cloud.githubusercontent.com/assets/20840700/19761864/e283e2a0-9c37-11e6-84c2-74da06acb27e.PNG)

**Comment by GrupImatica** [comment]
I attach PHP LOG:

[27-Oct-2016 12:29:40 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[27-Oct-2016 12:29:52 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[27-Oct-2016 12:30:02 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[27-Oct-2016 12:30:02 Asia/Kuwait] PHP Notice:  Undefined offset: 1 in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\download.php on line 110
[27-Oct-2016 12:30:02 Asia/Kuwait] PHP Fatal error:  Uncaught Error: Call to undefined function mime_content_type() in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\download.php:174
Stack trace:
#0 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\MVC\Controller\SugarController.php(864): require_once()
#1 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\MVC\Controller\SugarController.php(394): SugarController->handleEntryPoint()
#2 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\MVC\Controller\SugarController.php(307): SugarController->process()
#3 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\MVC\SugarApplication.php(105): SugarController->execute()
#4 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\index.php(52): SugarApplication->execute()
#5 {main}
  thrown in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\download.php on line 174
[27-Oct-2016 12:30:26 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[27-Oct-2016 12:30:31 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[27-Oct-2016 12:30:35 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[27-Oct-2016 12:30:36 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[27-Oct-2016 12:30:41 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162

**Comment by shogunpol** [comment]
After additional information i been able to replicate an issue in recent version of suiteCRM(7.7.6), however it appear only in Windows/MSSQL environment.
We label this issue as a "Bug"
@GrupImatica , thanks for your contribution.

**Comment by GrupImatica** [comment]
Hi, what is the planing of this Bug ?

We cannot use any file on any form of Suite CRM.

All getting error at opening files.

**Comment by GrupImatica** [comment]
@shogunpol, @willrennie , @JimMackin  Do you know where is the error for correct manually in our installation before the bug is fixed? We need this urgently :(

Thanks a lot.

Ivan

**Comment by sgaved** [comment]
This issue is caused by not having the Fileinfo extension enabled in php.ini.

**Comment by caspervzla** [comment]
Hi,

I have the same problem.

SuiteCRM Version used: 7.8.2
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 57.0.2987.133
Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5, PHP 5.3.8
Operating System and version (e.g Ubuntu 16.04): Windows Server 2008 R2
