### ISSUE TITLE
Issue in AOW Scheduled Task:

### ISSUE THREAD

**Issue by GrupImatica** [salesagility/SuiteCRM#2652]
Hi, im gettng error in Executing TASK with Scheduler Task for sending emails to Due Task.

I've created a Workflow with their conditions.

I go to execute task, and i get some errors in PHP70x64.log

`Stack trace:
#0 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_Actions\actions\actionSendEmail.php(275): actionSendEmail->getEmailsFromParams(Object(Task), Array)
#1 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_WorkFlow\AOW_WorkFlow.php(750): actionSendEmail->run_action(Object(Task), Array, false)
#2 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_WorkFlow\AOW_WorkFlow.php(139): AOW_WorkFlow->run_actions(Object(Task))
#3 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_WorkFlow\AOW_WorkFlow.php(125): AOW_WorkFlow->run_flow()
#4 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\Schedulers\_AddJobsHere.php(749): AOW_WorkFlow->run_flows()
#5 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\SchedulersJobs\SchedulersJob.php(536): processAOW_Workflow(Object(SchedulersJob))
#6 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\custom\modules\Schedul in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_Actions\actions\actionSendEmail.php on line 245
[16-Nov-2016 20:51:23 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:51:23 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:51:25 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:51:44 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:51:52 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:51:53 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:51:56 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:00 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:12 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:21 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:21 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:23 Asia/Kuwait] PHP Notice:  Trying to get property of non-object in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_Actions\actions\actionSendEmail.php on line 245
[16-Nov-2016 20:52:23 Asia/Kuwait] PHP Fatal error:  Uncaught Error: Call to a member function getPrimaryAddress() on null in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_Actions\actions\actionSendEmail.php:245
Stack trace:
#0 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_Actions\actions\actionSendEmail.php(275): actionSendEmail->getEmailsFromParams(Object(Task), Array)
#1 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_WorkFlow\AOW_WorkFlow.php(750): actionSendEmail->run_action(Object(Task), Array, false)
#2 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_WorkFlow\AOW_WorkFlow.php(139): AOW_WorkFlow->run_actions(Object(Task))
#3 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_WorkFlow\AOW_WorkFlow.php(125): AOW_WorkFlow->run_flow()
#4 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\Schedulers\_AddJobsHere.php(749): AOW_WorkFlow->run_flows()
#5 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\SchedulersJobs\SchedulersJob.php(536): processAOW_Workflow(Object(SchedulersJob))
#6 C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\custom\modules\Schedul in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_Actions\actions\actionSendEmail.php on line 245
[16-Nov-2016 20:52:24 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:24 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:24 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:24 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:24 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:24 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:26 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:26 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:27 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:27 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:27 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
[16-Nov-2016 20:52:27 Asia/Kuwait] PHP Warning:  Declaration of SugarEmailAddress::save($id, $module, $new_addrs = Array, $primary = '', $replyTo = '', $invalid = '', $optOut = '', $in_workflow = false) should be compatible with SugarBean::save($check_notify = false) in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\include\SugarEmailAddress\SugarEmailAddress.php on line 1162
`

Workflow works fine if i make conditions directly to after each new row make this or this, i receive email, and they create task without problems.

The AOW it's created to send notification to assigned user email, if task is due and has a different status of completed.

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All
* Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): WS 2012 R2

**Comment by shogunpol** [comment]
@GrupImatica ,to replicate this issue i must have more details, from this error log i cannot take information what i need. So: 
can you write step by step recreation path, 
can you provide all details about workFlow you created and what you want achieve by using it,
what task (details).

**Comment by GrupImatica** [comment]
Hi, we add line of table jobs_log

1	10c41075-fcc7-2e24-7205-58067f7096ef	Process Workflow Tasks	False	2016-10-18 20:02:32.000	2016-10-18 20:02:32.000	1f3916d4-1b5b-6ebe-269f-58021ed286e3	2016-10-18 20:02:00.000	done	success	Warning [2]: Invalid argument supplied for foreach() in C:\inetpub\wwwroot\GRUPIMATICA\SuiteCRM\modules\AOW_WorkFlow\AOW_WorkFlow.php on line 124
	function::processAOW_Workflow	NULL	False	NULL	NULL	0	CRONf7a6acbea2513e8ed160bcad745abbb6:3272	NULL

Database:
![aow1](https://cloud.githubusercontent.com/assets/20840700/20454633/cf3e1d5c-ae46-11e6-90ed-7a6d90b863b3.PNG)

Workflow:
![aow2](https://cloud.githubusercontent.com/assets/20840700/20454645/2a500606-ae47-11e6-8845-348b2293b2bd.PNG)

Task Scheduler
![aow3](https://cloud.githubusercontent.com/assets/20840700/20454646/2a658530-ae47-11e6-8c90-1d051f4de19c.PNG)

Properties:
![aow4](https://cloud.githubusercontent.com/assets/20840700/20454647/2a6e96de-ae47-11e6-9514-cc4e142aca33.PNG)

We can execute this manually with KickJob Extension
![aow5](https://cloud.githubusercontent.com/assets/20840700/20454648/2a78ac32-ae47-11e6-8638-557146fbfafb.PNG)

But, when i call Cron manually, same errors.

**Comment by shogunpol** [comment]
@GrupImatica , the settings from this workflow has been tested on recent version SuiteCRM(7.7.8), and work as expected, however on your instance i detect custom buttons: "PDF" and "Excel", addition of those may affect core functionalities. 
Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.

**Comment by GrupImatica** [comment]
Hi @shogunpol have you testet on MSSQL ?¿

I've removed sugarprint pluguin and doesnt works :(
