### ISSUE TITLE
Calendar body is not shown after PHP 7.x update

### ISSUE THREAD

**Issue by paullaz** [salesagility/SuiteCRM#3225]
#### Issue
Change from PHP 5.6 to 7.1 and calendar view disappears, headings exist.

#### Expected Behavior
Get to see the calendar

#### Actual Behavior
White space

#### Possible Fix
unknown

#### Steps to Reproduce
1. Upgrade from PHP 5.6 to 7.1
2. Go to Calendar.
3.
4.

#### Context
Fairly important

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version Firefox 51.0.1 or Chrome 56
![slv real estate-1](https://cloud.githubusercontent.com/assets/6889633/23591849/dfc375a6-01ab-11e7-86c4-9b3654d65764.png)

* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1.2
* Operating System and version (e.g Ubuntu 16.04): Centos 6.8

**Comment by paullaz** [comment]
Here is the log error of what I assume is probable cause:
[Sun Mar 05 17:47:36 2017] [error] [client 24.4.230.17] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/html/slvre-crm/modules/Calendar/CalendarDisplay.php:178\nStack trace:\n#0 /var/www/html/slvre-crm/modules/Calendar/index.php(99): CalendarDisplay->display()\n#1 /var/www/html/slvre-crm/include/MVC/View/SugarView.php(761): include_once('/var/www/html/s...')\n#2 /var/www/html/slvre-crm/include/MVC/View/views/view.classic.php(74): SugarView->includeClassicFile('modules/Calenda...')\n#3 /var/www/html/slvre-crm/include/MVC/View/SugarView.php(169): ViewClassic->display()\n#4 /var/www/html/slvre-crm/include/MVC/Controller/SugarController.php(363): SugarView->process()\n#5 /var/www/html/slvre-crm/include/MVC/Controller/SugarController.php(310): SugarController->processView()\n#6 /var/www/html/slvre-crm/include/MVC/SugarApplication.php(105): SugarController->execute()\n#7 /var/www/html/slvre-crm/index.php(52): SugarApplication->execute()\n#8 {main}\n  thrown in /var/www/html/slvre-crm/modules/Calendar/CalendarDisplay.php on line 178, referer: http://crm.slvre.com/index.php?module=Home&action=index

**Comment by paullaz** [comment]
Change line 178 of CalendarDisplay.php from:
$location_array = "";
to
$location_array = [];
Seems to solve the issue.
