### ISSUE TITLE
Schedules are not being validated on scheduled reports before saving them

### ISSUE THREAD

**Issue by adriangibanelbtactic** [salesagility/SuiteCRM#3457]
#### Issue
So the final user can deliberately save a wrong schedule on a scheduled report. This is a bug because that wrong save can make scheduled reports to be aborted when they encounter such wrong schedule.

#### Expected Behavior
The user should not be able to save a wrong schedule when editing/creating a scheduled report.

If the user is not able to save it then this won't be needed at all. I write it here just in case you want to make the code more resilient. Even if a wrong schedule is saved the scheduled reports should not exit but just skip that given scheduled report. Current behaviour issues an exception:
```
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message '00 07 19 04  is not a valid CRON expression' in /home/mycrm/public_html/modules/AOR_Scheduled_Reports/lib/Cron/CronExpression.php:99
Stack trace:
#0 /home/mycrm/public_html/modules/AOR_Scheduled_Reports/lib/Cron/CronExpression.php(84): Cron\CronExpression->setExpression('00 07 19 04 ')
#1 /home/mycrm/public_html/modules/AOR_Scheduled_Reports/lib/Cron/CronExpression.php(72): Cron\CronExpression->__construct('00 07 19 04 ', Object(Cron\FieldFactory))
#2 /home/mycrm/public_html/modules/AOR_Scheduled_Reports/AOR_Scheduled_Reports.php(179): Cron\CronExpression::factory('00 07 19 04 ')
#3 /home/mycrm/public_html/modules/Schedulers/_AddJobsHere.php(729): AOR_Scheduled_Reports->shouldRun(Object(DateTime))
#4 [internal function]: aorRunScheduledReports(Object(SchedulersJob))
#5 /home/mycrm/public_html/modules/SchedulersJobs/SchedulersJ in /home/mycrm/public_html/modules/AOR_Scheduled_Reports/lib/Cron/CronExpression.php on line 99
```

#### Actual Behavior
The user is able to save a wrong schedule when editing/creating a scheduled report.

#### Possible Fix
Maybe some javascript that checks the schedule before saving it?

#### Steps to Reproduce
1. Prepare to create a new Scheduled Report (AOR_Scheduled_Reports)
2. Click on Advanced so that it's selected.
3. Write: 
```
Min: "0" ; Hour: "0" ; Day: "*", Month="*" Day of week="" .
```
Where it means that you simply leave 'Day of the week' field blank.
4. Save.

#### Context
This bug affected users that were expecting they associated scheduled reports and, suddenly, they didn't receive them.

I think this is a medium bug because, even if final users are not supposed to use schedules in advanced mode if they do it should be resilient in case of error.

#### Your Environment
* SuiteCRM Version used: 7.7.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Google Chromium Version 57.0.2987.98
* Environment name and version (e.g. MySQL, PHP 7): php 5.5.59, mysql 5.5.54
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by Kevconry** [comment]
was able to replicate in 7.13.2
