### ISSUE TITLE
Unable to create or edit projects

### ISSUE THREAD

**Issue by Pontecerca** [salesagility/SuiteCRM#6346]
#### Issue
Cant create or edit projects.
Suitecrm log on create project:

`Fri Sep 21 12:27:47 2018 [23045][1][FATAL] Exception handling in /home/****/public_html/include/MVC/Controller/SugarController.php:400
Fri Sep 21 12:27:47 2018 [23045][1][FATAL] Exception in Controller: Error al recuperar registro.  Este registro puede haber sido eliminado o puede que no esté autorizado para verlo.
Fri Sep 21 12:27:47 2018 [23045][1][FATAL] backtrace:
#0 /home/****/public_html/include/MVC/View/views/view.detail.php(102): sugar_die('Error al recupe...')
#1 /home/****/public_html/modules/Project/views/view.detail.php(79): ViewDetail->display()
#2 /home/****/public_html/include/MVC/View/SugarView.php(211): ProjectViewDetail->display()
#3 /home/****/public_html/include/MVC/Controller/SugarController.php(435): SugarView->process()
#4 /home/****/public_html/include/MVC/Controller/SugarController.php(375): SugarController->processView()
#5 /home/****/public_html/include/MVC/SugarApplication.php(113): SugarController->execute()
#6 /home/****/public_html/index.php(52): SugarApplication->execute()
#7 {main}`

Chrome console js error on edit/create view:

`sugar_grp_project.js:121 Uncaught TypeError: Cannot read property 'getFullYear' of null
    at SugarWidgetSchedulerAttendees.init (sugar_grp_project.js:121)
    at new SugarWidgetSchedulerAttendees (sugar_grp_project.js:115)
    at SugarWidgetScheduler.display (sugar_grp_project.js:103)
    at SugarWidgetScheduler.load (sugar_grp_project.js:93)
    at SugarContainer.start (sugar_grp_project.js:7)
    at YAHOO.util.YUILoader.onSuccess (index.php?module=Project&action=EditView&return_module=Project&return_action=DetailView:1327)
    at YAHOO.util.YUILoader.loadNext (sugar_grp1.js?v=U5KyHpauODs9FocOZqTQvw:865)
    at YAHOO.util.YUILoader.donext (sugar_grp1.js?v=U5KyHpauODs9FocOZqTQvw:865)
    at c (sugar_grp1.js?v=U5KyHpauODs9FocOZqTQvw:865)
    at f (sugar_grp1.js?v=U5KyHpauODs9FocOZqTQvw:865)`

Php error.log empty
Permisions:
644 file
755 dirs
775 custom cache themes  modules  data upload config_override.php

Administrator account

Quick repair  unsucesfully

Revert all modules customizations and error continues

SuiteCRM 7.10.7, upgrading to 7.10.9 error continues

#### Steps to Reproduce

1. Open project for edit 
2. Change some values
3. Save changes
4. Page refresh to projects view but changes no effect

#### Your Environment

* SuiteCRM Version used: 7.10.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):php 7.0
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by samus-aran** [comment]
Closing due to inactivity.
