### ISSUE TITLE
Database Failure when creating a Meeting

### ISSUE THREAD

**Issue by bwlinux** [salesagility/SuiteCRM#6377]
#### Issue
Scheduling a meeting from within a Lead, I set the start date and time, then click save.
Database Failure error is displayed on a white screen
This was not a problem with 7.10.7

#### Expected Behavior
After clicking Save, it should take me back to the Lead's information.

#### Actual Behavior
It displays a white page with the phrase database failure.  The relevant log entries are

Tue Oct  2 10:42:05 2018 [9248][84044521-900b-9697-46ca-5a444fb607c4][FATAL] lead name
Tue Oct  2 10:42:05 2018 [9248][84044521-900b-9697-46ca-5a444fb607c4][FATAL] Mr. Boss Brian
Tue Oct  2 10:42:05 2018 [9248][84044521-900b-9697-46ca-5a444fb607c4][ERROR] fromUser: Conversion of 2018-10-02 15:42:05 from user format m/d/Y h:ia failed
Tue Oct  2 10:42:05 2018 [9248][84044521-900b-9697-46ca-5a444fb607c4][ERROR] fromUser: Conversion of 2018-10-02 15:42:05 from user format m/d/Y h:ia failed
Tue Oct  2 10:42:05 2018 [9248][84044521-900b-9697-46ca-5a444fb607c4][FATAL] Mysqli_query failed.
Tue Oct  2 10:42:05 2018 [9248][84044521-900b-9697-46ca-5a444fb607c4][FATAL]  Query Failed: SELECT meetings.* from meetings_users,meetings  WHERE ((meetings.date_start >= '2018-10-01 05:00:00' AND meetings.date_sta                                         rt < '2018-12-01 06:00:00') OR (meetings.date_start < '2018-10-01 05:00:00' AND meetings.date_end > '2018-10-01 05:00:00') AND meetings_users.accept_status != 'decline') AND : MySQL error 1064: You have an error in                                          your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
Tue Oct  2 10:42:05 2018 [9248][84044521-900b-9697-46ca-5a444fb607c4][FATAL] Exception handling in /var/www/vhosts/crm.rockhopper/include/MVC/Controller/SugarController.php:400
Tue Oct  2 10:42:05 2018 [9248][84044521-900b-9697-46ca-5a444fb607c4][FATAL] Exception in Controller: Database failure. Please refer to suitecrm.log for details.
Tue Oct  2 10:42:05 2018 [9248][84044521-900b-9697-46ca-5a444fb607c4][FATAL] backtrace:
#0 /var/www/vhosts/crm.rockhopper/include/database/DBManager.php(353): sugar_die('Database failur...')
#1 /var/www/vhosts/crm.rockhopper/include/database/DBManager.php(328): DBManager->registerError(' Query Failed: ...', ' Query Failed: ...', true)
#2 /var/www/vhosts/crm.rockhopper/include/database/MysqliManager.php(179): DBManager->checkError(' Query Failed: ...', true)
#3 /var/www/vhosts/crm.rockhopper/include/utils/activity_utils.php(90): MysqliManager->query('SELECT meetings...', true)
#4 /var/www/vhosts/crm.rockhopper/modules/Calendar/CalendarActivity.php(263): build_related_list_by_user_id(Object(Meeting), '84044521-900b-9...', '((meetings.date...')
#5 /var/www/vhosts/crm.rockhopper/modules/vCals/vCal.php(153): CalendarActivity::get_activities(Array, '84044521-900b-9...', false, Object(SugarDateTime), Object(SugarDateTime), 'freebusy')
#6 /var/www/vhosts/crm.rockhopper/modules/vCals/vCal.php(231): vCal->create_sugar_freebusy(Object(User), Object(SugarDateTime), Object(SugarDateTime))
#7 /var/www/vhosts/crm.rockhopper/modules/vCals/vCal.php(260): vCal->get_vcal_freebusy(Object(User), false)
#8 /var/www/vhosts/crm.rockhopper/modules/vCals/vCal.php(247): vCal::cache_sugar_vcal_freebusy(Object(User))
#9 /var/www/vhosts/crm.rockhopper/modules/Meetings/MeetingFormBase.php(472): vCal::cache_sugar_vcal(Object(User))
#10 /var/www/vhosts/crm.rockhopper/modules/Meetings/Save.php(55): MeetingFormBase->handleSave('', true, false)
#11 /var/www/vhosts/crm.rockhopper/include/MVC/View/SugarView.php(818): include_once('/var/www/vhosts...')
#12 /var/www/vhosts/crm.rockhopper/include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile('modules/Meeting...')
#13 /var/www/vhosts/crm.rockhopper/include/MVC/View/SugarView.php(211): ViewClassic->display()
#14 /var/www/vhosts/crm.rockhopper/include/MVC/Controller/SugarController.php(435): SugarView->process()
#15 /var/www/vhosts/crm.rockhopper/include/MVC/Controller/SugarController.php(375): SugarController->processView()
#16 /var/www/vhosts/crm.rockhopper/include/MVC/SugarApplication.php(113): SugarController->execute()
#17 /var/www/vhosts/crm.rockhopper/index.php(52): SugarApplication->execute()
#18 {main}

#### Possible Fix
Not sure, but it looks like the SQL is wrong or incomplete

#### Steps to Reproduce

1. Open a lead
2. In the Activities panel, select Schedule Meeting
3. Enter Subject and Start Date, Click Save
4. Database Failure!

#### Context
I'm trying to create a meeting for a lead that's coming in.
This is business interrupting.

#### Your Environment

* SuiteCRM Version used: 7.10.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 69.0.3497.100
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.1.36, php 7.1.22 
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by bwlinux** [comment]
Never mind.....
After comparing a fresh, prestine copy of 7.10.9 against my production system which has the paid for SecuritySuite module installed, I traced the bug down to a problem in that module.  Specifically in the include/utils/activity_utils.php file.
