### ISSUE TITLE
Suite 7.8.21: Inbound Emails dont get pulled

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#6438]
After Update from 7.8.20 to 7.8.21 I cannot pull emails anymore. Cron-Job throws following error (run as www-data):

```
PHP Fatal error:  Uncaught Error: Class 'SuiteCRM\StateSaver' not found in /var/www/crm.nk.be/modules/InboundEmail/InboundEmail.php:5086
Stack trace:
#0 /var/www/crm.nk.be/modules/InboundEmail/InboundEmail.php(4951): InboundEmail->getImapConnection('{192.168.29.111...', 'suite_be', '...', 32768)
#1 /var/www/crm.nk.be/modules/Schedulers/_AddJobsHere.php(564): InboundEmail->connectMailserver()
#2 /var/www/crm.nk.be/modules/SchedulersJobs/SchedulersJob.php(549): pollMonitoredInboxesAOP(Object(SchedulersJob))
#3 /var/www/crm.nk.be/include/SugarQueue/SugarCronJobs.php(188): SchedulersJob->runJob()
#4 /var/www/crm.nk.be/include/SugarQueue/SugarCronJobs.php(228): SugarCronJobs->executeJob(Object(SchedulersJob))
#5 /var/www/crm.nk.be/cron.php(96): SugarCronJobs->runCycle()
#6 {main}
  thrown in /var/www/crm.nk.be/modules/InboundEmail/InboundEmail.php on line 5086
```

If i try to run cron.php as other user than www-data i get following:

```
gunni@grunthos:/var/www/crm.nk.be$ php -f cron.php
Composer autoloader not found. please run "composer install"
```

In suitecrm.log i get folowing error:

`Mon Oct 22 15:53:03 2018 [48519][1][FATAL] Job a7ad4eb4-d77e-fbde-f625-5bcdd614967f (Check Inbound Mailboxes) failed in CRON run`

SuiteCRM-Version 7.8.21
PHP-Version 7.2.10
OS: Ubuntu 18.04

**Comment by Dillon-Brown** [comment]
This was due to an error with the upgrade packs. It should be resolved in 7.8.22 and above.
