### ISSUE TITLE
Removing custom view fails

### ISSUE THREAD

**Issue by vladaman** [salesagility/SuiteCRM#6776]
SuiteCRM 7.11.0 - When removing custom module from studio I get following error and exception. The module has no features, I just used new Case module template, created new module, deployed and then trying to remove.

```
DeployedMetaDataImplementation->getFileName(): View Array is not recognized
```

```
Thu Jan 17 11:18:56 2019 [17642][2c0f3bb8-55b5-7ea5-817e-5a8e74b5e482][FATAL] Exception handling in /var/www/crm/SuiteCRM-7.11.0/include/MVC/Controller/SugarController.php:402
Thu Jan 17 11:18:56 2019 [17642][2c0f3bb8-55b5-7ea5-817e-5a8e74b5e482][FATAL] Exception in Controller: DeployedMetaDataImplementation->getFileName(): View Array is not recognized
Thu Jan 17 11:18:56 2019 [17642][2c0f3bb8-55b5-7ea5-817e-5a8e74b5e482][FATAL] backtrace:
#0 /var/www/crm/SuiteCRM-7.11.0/modules/ModuleBuilder/parsers/views/DeployedMetaDataImplementation.php(368): sugar_die('DeployedMetaDat...')
#1 /var/www/crm/SuiteCRM-7.11.0/modules/ModuleBuilder/parsers/views/DeployedMetaDataImplementation.php(114): DeployedMetaDataImplementation->getFileName(Array, 'TripTracker', NULL, 'base')
#2 /var/www/crm/SuiteCRM-7.11.0/modules/ModuleBuilder/views/view.resetmodule.php(179): DeployedMetaDataImplementation->__construct(Array, 'TripTracker')
#3 /var/www/crm/SuiteCRM-7.11.0/modules/ModuleBuilder/views/view.resetmodule.php(106): ViewResetmodule->removeCustomLayouts()
#4 /var/www/crm/SuiteCRM-7.11.0/modules/ModuleBuilder/views/view.resetmodule.php(68): ViewResetmodule->handleSave()
#5 /var/www/crm/SuiteCRM-7.11.0/include/MVC/View/SugarView.php(226): ViewResetmodule->display()
#6 /var/www/crm/SuiteCRM-7.11.0/include/MVC/Controller/SugarController.php(432): SugarView->process()
#7 /var/www/crm/SuiteCRM-7.11.0/include/MVC/Controller/SugarController.php(375): SugarController->processView()
#8 /var/www/crm/SuiteCRM-7.11.0/include/MVC/SugarApplication.php(109): SugarController->execute()
#9 /var/www/crm/SuiteCRM-7.11.0/index.php(52): SugarApplication->execute()
```

**Comment by cameronblaikie** [comment]
Hi there @vladaman,
Can you show me where this case module is, please.
thanks

**Comment by willrennie** [comment]
Closing due to inactivity. If this is still an issue, please update
