### ISSUE TITLE
 campaign page failure/imapfactory

### ISSUE THREAD

**Issue by heytimc** [salesagility/SuiteCRM#6810]
#### Issue
 Campaign "Set up Email" page (and other related campaign pages) is blank after upgrading to 7.11.0

#### Actual Behavior
Apache log reports:
PHP Fatal error: Uncaught Error: Class 'ImapHandlerFactory' not found in /var/www/html/crm/modules/Campaigns/WizardEmailSetup.php:182
Stack trace:
#0 /var/www/html/crm/include/MVC/View/SugarView.php(832): include_once()
#1 /var/www/html/crm/modules/Campaigns/views/view.classic.php(78): SugarView->includeClassicFile('modules/Campaig...')
#2 /var/www/html/crm/include/MVC/View/SugarView.php(226): CampaignsViewClassic->display()
#3 /var/www/html/crm/include/MVC/Controller/SugarController.php(432): SugarView->process()
#4 /var/www/html/crm/include/MVC/Controller/SugarController.php(375): SugarController->processView()
#5 /var/www/html/crm/include/MVC/SugarApplication.php(109): SugarController->execute()
#6 /var/www/html/crm/index.php(52): SugarApplication->execute()
#7 {main}
thrown in /var/www/html/crm/modules/Campaigns/WizardEmailSetup.php on line 182, referer: XXXXXXXX

#### Steps to Reproduce
1. Install brand new 7.11.0 or 7.10.12 SuiteCRM
2. Log in
3. Go to Campaigns page
4. Click "Set up Email" on the left

#### Context
Completely unable to use campaign email system beyond configuration of a campaign

#### Your Environment
SuiteCRM 7.11.0
Sugar Version 6.5.25 (Build 344)
CentOS Linux release 7.6.1810 (Core)
Server version: Apache/2.4.6 (CentOS)
PHP 7.0.33 (cli) (built: Jan 9 2019 14:57:19) ( NTS )
mysql Ver 15.1 Distrib 10.3.12-MariaDB, for Linux (x86_64) using readline 5.1 
Problem seen in all browsers; its a server-side issue

**Comment by heytimc** [comment]
Works for me - thanks!
