### ISSUE TITLE
Mysql insert error on Google Calendar Sync

### ISSUE THREAD

**Issue by matthewmalk248** [salesagility/SuiteCRM#6892]
#### Issue
My google cal was syncing both ways previously but now only syncs from SuiteCRM to Google and not from Google to SuiteCRM, noticed this Mysql error in suitecrm.log

at Feb  2 17:35:04 2019 [16035][1][FATAL] Mysqli_query failed.
Sat Feb  2 17:35:04 2019 [16035][1][FATAL]  Query Failed: UPDATE meetings SET gsync_id = '' WHERE id = REDACTED-6305-107b-3427-REDACTED: MySQL error 1054: Unknown column '79fd8efb' in 'where clause'
Sat Feb  2 17:35:04 2019 [16035][1][FATAL] /home/mydomain/public_html/include/GoogleSync/GoogleSyncBase.php:713 GoogleSyncBase::delEvent - Failed to remove gsync_id from record7REDACTED-6305-107b-3427-REDACTED

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
@ApatheticCosmos do you have any idea what that could be causing this?

**Comment by ApatheticCosmos** [comment]
Can we please get a full log of the process? Set the log level to debug and don't react anything. There's nothing sensitive in there other than possibly the subject/title of the event. The ID is just the random uuid if the suitecrm meeting.

**Comment by ApatheticCosmos** [comment]
I've been looking at the code where this failure is happening, and I can't figure out how it could be looking for a column named '79fd8efb'. I thought maybe there was a space in the id somehow... which would be weird enough. But if there was a space it wouldn't have passed validation before it gets here.

It's at line 710 of include/GoogleSync/GoogleSyncBase.php
```
$sql = "UPDATE meetings SET gsync_id = '' WHERE id = {$valMeetingId}";
$res = $this->db->query($sql);
if (!$res) {
    $this->logger->fatal(__FILE__ . ':' . __LINE__ . ' ' . __METHOD__ . ' - ' . 'Failed to remove gsync_id from record' . $valMeetingId);
}
```
This gets run when an event is deleted on the SuiteCRM side of the sync. It removes Google's internal ID of the event from the SuiteCRM record.

**Comment by pribeiro42** [comment]
Shouldn't the id value be quoted, like:

`$sql = "UPDATE meetings SET gsync_id = '' WHERE id = '{$valMeetingId}'" ;
`
Because without the quotes, MySQL might assume that you want to pass the value of a column to another column...

**Comment by ApatheticCosmos** [comment]
@pribeiro42 Not in this case, because $valMeetingId is created by
```
$valMeetingId = $this->db->quote($meeting_id);
```
Quoting it in the $sql string will result in double quoting and a failed query.

**Comment by pribeiro42** [comment]
@ApatheticCosmos ah, ok then...

**Comment by pribeiro42** [comment]
@ApatheticCosmos, I went and checked the code and it looks like the 

`$this->db->quote($string)`

only quotes the string's characters, and the

`$this->db->quoted($string) `

puts the string inside quotes..

Please check line 734 of the same file include/GoogleSync/GoogleSyncBase.php on the clearPopups function:

`$eventIdQuoted = $this->db->quoted($event_id);`

So, i think if the line 694 changes to:

`$valMeetingId = $this->db->quoted($meeting_id) ; `

the problem goes away...

**Comment by ApatheticCosmos** [comment]
@pribeiro42 I think you're on to something. quoted() is what is needed here, and quote() escapes chars in the string.
What a crazy typo. It's not the only place, either.

**Comment by pribeiro42** [comment]
@ApatheticCosmos it had to be some quoting problem, to turn a string into a column name ;)

**Comment by matthewmalk248** [comment]
Sounds like I'm late to the party, did you guys still need me to set debug and gather more logs?

**Comment by pribeiro42** [comment]
I'm not really debugging.. don't even run the code, i've just took a look, so, be my guest and, if like @ApatheticCosmos said, there are more places with this typo i guess it doesn't hurt to gather more info...

**Comment by ApatheticCosmos** [comment]
@matthewmalk248 Try this...
Go into the file include/GoogleSync/GoogleSyncBase.php and edit line 694
Change it from
```
$valMeetingId = $this->db->quote($meeting_id);
```
To:
```
$valMeetingId = $this->db->quoted($meeting_id);
```

If that solves the problem, we'll know what the problem is and I can create a patch.
I would also set your log level to debug so you can get a full log of the process.

**Comment by matthewmalk248** [comment]
Made the change and it now appears sync has stopped working in either direction,  here's the log
https://www.dropbox.com/s/6gt9lprs1cy473g/suitecrmlog.txt?dl=0

**Comment by matthewmalk248** [comment]
1-way stopped working now too, hmm, also just noticed everytime I click on a day to put in an appt , it puts it back a day when I save it. (e.g. I clicked on 1pm Thursday the 6th, the new calendar event window appeared and showed 1pm thursday on the date selection field, but when i save, it saves it to 1pm Wedesday the 5th) then I have to drag it back to the correct day. Dont know if that is possibly related?

**Comment by matthewmalk248** [comment]
the cron job wont work (even manually), ignore everything i just said until I can get it running :)

**Comment by ApatheticCosmos** [comment]
@matthewmalk248 I think the 'new event one day back' thing is a UI bug. I thought it was fixed though. If you reload the page you should see it on the correct day.

**Comment by pribeiro42** [comment]
@matthewmalk248 but the [FATAL] error doesn't show up in the log... so, the way I see it, the query is executing fine...

**Comment by matthewmalk248** [comment]
So the change resolved the FATAL error, but the calendar just isn't showing the items retrieved from Google?  Should I look in  a db table somewhere to see if they are being retrieved, just not shown?

**Comment by ApatheticCosmos** [comment]
I've downloaded the log. Give me a bit to look it over. It does show a failure.

**Comment by matthewmalk248** [comment]
k standing by, I checked in the meetings db table and the meetings created in google are not getting Inserted in there.

**Comment by ApatheticCosmos** [comment]
Here's what's getting logged:
```
Mon Feb  4 13:27:10 2019 [18721][1][FATAL] Caught Exception While Syncing User:a57da642-4e1c-4a79-35d4-5aa9656176a1
Mon Feb  4 13:27:10 2019 [18721][1][ERROR] #0 /home/crmbezalu/public_html/include/GoogleSync/GoogleSync.php(163): GoogleSyncBase->getMeetingByEventId('ocui3tl0pkk1f2u...')
#1 /home/crmbezalu/public_html/include/GoogleSync/GoogleSync.php(297): GoogleSync->doSync('a57da642-4e1c-4...')
#2 /home/crmbezalu/public_html/modules/Schedulers/_AddJobsHere.php(533): GoogleSync->syncAllUsers()
#3 /home/crmbezalu/public_html/modules/SchedulersJobs/SchedulersJob.php(542): syncGoogleCalendar(Object(SchedulersJob))
#4 /home/crmbezalu/public_html/include/SugarQueue/SugarCronJobs.php(191): SchedulersJob->runJob()
#5 /home/crmbezalu/public_html/include/SugarQueue/SugarCronJobs.php(231): SugarCronJobs->executeJob(Object(SchedulersJob))
#6 /home/crmbezalu/public_html/cron.php(99): SugarCronJobs->runCycle()
#7 {main}
```
So... my logging code sucks. I need fix that so I can figure out what exception it's hitting. It's not in the trace. Please change line 300 of include/GoogleSync/GoogleSync.php from this:
```
$this->logger->fatal('Caught Exception While Syncing User:' . $key);
```
To this:
```
$this->logger->fatal('Caught Exception Number '.  $e->getCode() . ' While Syncing User: ' . $key);
```

Then when the sync fails I'll be able to reference the code and know exactly where it's being thrown.

**Comment by matthewmalk248** [comment]
well it's better than mine lol
Updated log after change to line 300..
https://www.dropbox.com/s/b2pi3nuex9kcdaj/suitelog3.txt?dl=0

**Comment by ApatheticCosmos** [comment]
Oh... oh boy.
The exception is being thrown at include/GoogleSync/GoogleSyncBase.php:498
That doesn't make any sense... unless there is a meeting in the DB that is corrupted.
Can you run some SQL commands for me?
It might be better to take this over to https://gitter.im/SuiteCRM_AC/community
so we can debug in real time.

**Comment by ApatheticCosmos** [comment]
After doing some out-of-band troubleshooting, it seems that something corrupted one of the meeting records. After clearing the records Sync started working again.
The $db->quote() vs $db-quoted() issue is suspect.

**Comment by cameronblaikie** [comment]
Hi @ApatheticCosmos , From looking through the history it seems your issue has been resolved, I am going to close this issue now and if there are further problems then we will reopen the issue.
Thanks,
