### ISSUE TITLE
Exception in Controller: Some garbage state left in stack (did you pop everything?) 

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#7859]
#### Issue

From the [forum](https://suitecrm.com/suitecrm/forum/installation-upgrade-help/27407-upgrade-7-10-19-lts-to-7-10-20-lts-failed#89340)

I open this issue hoping the [Linus's Law](https://en.wikipedia.org/wiki/Linus's_Law) can help us ;-)

In my laptop my instance was working OK, until a DB error appears. After that, seems that this error was 'cached' and no matter what you do, the following error appears in the log.

SuiteCRM log:

```
Fri Sep 13 17:09:24 2019 [26554][5631d153-b056-1e59-180d-5d5c458a91c4][FATAL] Error filling in additional detail fields: Query Failed: SELECT name , assigned_user_id parent_name_owner from contacts where id = '': MySQL error 1054: Unknown column 'name' in 'field list'
Fri Sep 13 17:09:24 2019 [26554][5631d153-b056-1e59-180d-5d5c458a91c4][FATAL] Exception handling in /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php:400
Fri Sep 13 17:09:24 2019 [26554][5631d153-b056-1e59-180d-5d5c458a91c4][FATAL] Exception in Controller: Some garbage state left in stack (did you pop everything?) Needs to restore: [error_reporting.sugar_smarty_errors] => 'sugar_smarty_errors'
Fri Sep 13 17:09:24 2019 [26554][5631d153-b056-1e59-180d-5d5c458a91c4][FATAL] backtrace:
#0 /home/jose/trabajos/gca-suitecrm7.10x/include/Sugar_Smarty.php(164): SuiteCRM\StateSaver->__destruct()
#1 /home/jose/trabajos/gca-suitecrm7.10x/vendor/smarty/smarty/libs/Smarty.class.php(1113): Sugar_Smarty->fetch('themes/BCCL/tpl...', NULL, NULL, true)
#2 /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/SugarView.php(683): Smarty->display('themes/BCCL/tpl...')
#3 /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/SugarView.php(100): CustomSugarView->displayHeader()
#4 /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php(435): CustomSugarView->process()
#5 /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php(375): SugarController->processView()
#6 /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/SugarApplication.php(113): SugarController->execute()
#7 /home/jose/trabajos/gca-suitecrm7.10x/index.php(80): SugarApplication->execute()
#8 {main}
Fri Sep 13 17:09:24 2019 [26554][5631d153-b056-1e59-180d-5d5c458a91c4][FATAL] Previous:
Fri Sep 13 17:09:24 2019 [26554][5631d153-b056-1e59-180d-5d5c458a91c4][FATAL] Exception in Controller: Error de base de datos. Por favor, consulte SuiteCRM error .log para más detalles.
Fri Sep 13 17:09:24 2019 [26554][5631d153-b056-1e59-180d-5d5c458a91c4][FATAL] backtrace:
#0 /home/jose/trabajos/gca-suitecrm7.10x/include/database/DBManager.php(353): sugar_die('Error de base d...')
#1 /home/jose/trabajos/gca-suitecrm7.10x/include/database/DBManager.php(328): DBManager->registerError(' Error filling
...', ' Error filling ...', true)
#2 /home/jose/trabajos/gca-suitecrm7.10x/custom/include/database/MysqliManagerGcoop.php(41): DBManager->checkError(' Error filling ...', true, false)
#3 /home/jose/trabajos/gca-suitecrm7.10x/modules/Tasks/Task.php(218): MysqliManagerGcoop->query('SELECT name , ...', true, ' Error filling ...')
#4 /home/jose/trabajos/gca-suitecrm7.10x/data/SugarBean.php(4838): Task->fill_in_additional_parent_fields()
#5 /home/jose/trabajos/gca-suitecrm7.10x/modules/Tasks/Task.php(167): SugarBean->fill_in_additional_detail_fields()
#6 /home/jose/trabajos/gca-suitecrm7.10x/data/SugarBean.php(4565): Task->fill_in_additional_detail_fields()
#7 /home/jose/trabajos/gca-suitecrm7.10x/data/BeanFactory.php(104): SugarBean->retrieve('50625416-4808-8...', true, true)
#8 /home/jose/trabajos/gca-suitecrm7.10x/include/Smarty/plugins/function.suite_check_access.php(35): BeanFactory::getBean('Tasks', '50625416-4808-8...')
#9 /home/jose/trabajos/gca-suitecrm7.10x/cache/smarty/templates_c/%%30^30B^30B88B75%%_headerModuleList.tpl.php(131): smarty_function_suite_check_access(Array, Object(Sugar_Smarty))
#10 /home/jose/trabajos/gca-suitecrm7.10x/vendor/smarty/smarty/libs/Smarty.class.php(1876): include('/home/jose/trab...')
#11 /home/jose/trabajos/gca-suitecrm7.10x/cache/smarty/templates_c/%%B7^B79^B79695C8%%header.tpl.php(13): Smarty->_smarty_include(Array)
#12 /home/jose/trabajos/gca-suitecrm7.10x/vendor/smarty/smarty/libs/Smarty.class.php(1263): include('/home/jose/trab...')
#13 /home/jose/trabajos/gca-suitecrm7.10x/include/Sugar_Smarty.php(164): Smarty->fetch('themes/BCCL/tpl...', NULL, NULL, true)
#14 /home/jose/trabajos/gca-suitecrm7.10x/vendor/smarty/smarty/libs/Smarty.class.php(1113): Sugar_Smarty->fetch('themes/BCCL/tpl...', NULL, NULL, true)
#15 /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/SugarView.php(683): Smarty->display('themes/BCCL/tpl...')
#16 /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/SugarView.php(100): CustomSugarView->displayHeader()
#17 /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php(435): CustomSugarView->process()
#18 /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php(375): SugarController->processView()
#19 /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/SugarApplication.php(113): SugarController->execute()
#20 /home/jose/trabajos/gca-suitecrm7.10x/index.php(80): SugarApplication->execute()
#21 {main}
```

And SuiteCRM looks like this:

![imagen](https://user-images.githubusercontent.com/939888/64895005-a1fe3f80-d651-11e9-8428-66f0749f13c8.png)

Doing a git bisect between HEAD and commit e3a8e6049 I found that the first bad commit is:

```
Head:     a61c8d8e0 Move Smarty from include/ to Composer.
Tags:     v7.10.18-cf (101), v7.10.20 (152)

a61c8d8e0aac3ca0f5ff9eed79c089e016a917ad is the first bad commit
commit a61c8d8e0aac3ca0f5ff9eed79c089e016a917ad
Author: Connor Shea <connor.james.shea@gmail.com>
Date:   Wed Jul 17 15:54:18 2019 -0600
    Move Smarty from include/ to Composer.
    
    This keeps the Smarty/plugins directory for now.
    
    Removes the security-advisories package because it was
    preventing me from installing Smarty.
:100644 100644 58498a7ac496f2696c065e703ca36c17d208dafc 041c48ffcea3e5a4a53d7f114de800f3392cde77 M	codeception.yml
:100644 100644 ae0bd2c9f7897a70f86f36bec885879534ba383e 137a7ec6e80cc50a7c39cd44d5e1bde81330d6d9 M	composer.json
:100644 100644 01f8ff8d9dbf837f428924dc52e58acebf296392 fec18c779eab9481d889ab301bdc0bd55df638c9 M	composer.lock
:040000 040000 4fcb24b29f6e2ec23f1192ed2619e6481c08622e 3b3217567944f9b45a6f5855a105b3ed18569166 M	include

Bisect Rest (1)
a61c8d8e0 * bad @ Move Smarty from include/ to Composer.

Bisect Log (13)
git bisect start 'release/1' 'e3a8e6049'
8e1970dfc bad FIX SU_BUG_65 - Migramos customizaciones de Leads
e3a8e6049 good Merge pull request #7670 from salesagility/hotfix-7.10.x

git bisect good 404ba3c8ae9873e2b5b24418af221858956e18e0
404ba3c8a good REL #37231 - Mover el SubPanelViewer de contacts a custom/modules/Contacts y descomentar el retrieve x idt24 antes de traer el subpanel

git bisect good 5147056450e399ac7651a71c8198199cbaf50127
514705645 good Remove demo test suite.

git bisect good cd91ffb5dff47668b5b4fb54217a78db4bc83bab
cd91ffb5d good REL #39605 - Mergear el config_ws.php de ssug2001lx con el actual nuestro del entorno de testing

git bisect bad 9c80acd63a4f511674802ec7fc5a5956efbd39a9
9c80acd63 bad Merge branch 'develop' into release/1

git bisect bad b3c1cdab0ec7e3404551632d47fee02144d49f7b
b3c1cdab0 bad Merge branch 'LTS' into develop

git bisect bad b7fc21e5a024c35785f10f4957c369be13b4f6c6
b7fc21e5a bad Merge pull request #7698 from Dillon-Brown/suitebot_config

git bisect bad f849f98c754aff0424b75372a8749b61fff2aef0
f849f98c7 bad Fix logger

git bisect bad ab17e2e94cb5734357ef9818d877261e6a70f410
ab17e2e94 bad Merge pull request #10 from salesagility/hotfix-7.10.x

git bisect bad 68a18d6c872be12553caf01a8bad30386a94a84d
68a18d6c8 bad Fix header.tpl includes.

git bisect bad 6f566a7c410ffcdfb6b0e02ae934885626d23ab6
6f566a7c4 bad Remove theme_template from smarty includes.

git bisect bad a61c8d8e0aac3ca0f5ff9eed79c089e016a917ad
a61c8d8e0 bad Move Smarty from include/ to Composer.

a61c8d8e0aac3ca0f5ff9eed79c089e016a917ad is the first bad commit
```

Keep investigating...

#### Expected Behavior

None of the above happens

#### Possible Fix

I still have no idea

#### Steps to Reproduce

I cannot provide a way to reproduce it, I only know that I tried to do a search that performs an invalid Query and after that, the error appears in the log and the instance is broken.

#### Your Environment

* SuiteCRM Version used: 7.10.20
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 68
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.3 MySQL 8
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 19.04 / Debian 10

**Comment by Abuelodelanada** [comment]
@connorshea  can you take a look?

**Comment by Abuelodelanada** [comment]
I found the bug, not a problem in SuiteCRM, but in some of our custom code. I do not yet why, but started with the Smarty change.

I close this issue and keep investigating if there is something to improve.
