### ISSUE TITLE
Time Type field is not saved and Generate Fatal error

### ISSUE THREAD

**Issue by kishah2411** [salesagility/SuiteCRM#7983]
**Time Type field is not saved and Generate Fatal error** 

#### Issue
In Suitecrm Older version I have created a custom field using "time" type.
When I upgrade suitecrm to 7.11.7 version then due to this field type I am facing 500 fatal error into PHP error log
If I am creating custom field in Account then It is working. But same code is not working for Document Module Or my Custom module.

I am using the following code for create time type fields.
'time_from' => array(
			'name' => 'time_from',
			'vname' => 'LBL_TIME_FROM',
			'type' => 'time',
			'required' => false,
			'reportable' => false,
		),

#### Expected Behavior
Without any Error need to save time field into Database

#### Actual Behavior
When Save this page then redirect to Fatal error Page and Generated following log:

[b] [client ::1:52034] PHP Warning:  Declaration of SugarFieldTime::save(&$bean, &$inputData, &$field, &$def, $prefix = '') should be compatible with SugarFieldBase::save(&$bean, $params, $field, $properties, $prefix = '') in /var/www/html/crm/include/SugarFields/Fields/Time/SugarFieldTime.php on line 0, referer: https://localhost/crm/index.php?module=master_shift&action=EditView&return_module=master_shift&return_action=DetailView
 [client ::1:52034] PHP Fatal error:  Uncaught Error: Cannot pass parameter 2 by reference in /var/www/html/crm/include/MVC/Controller/SugarController.php:649\nStack trace:\n#0 /var/www/html/crm/include/MVC/Controller/SugarController.php(504): SugarController->pre_save()\n#1 /var/www/html/crm/include/MVC/Controller/SugarController.php(491): SugarController->pre_action()\n#2 /var/www/html/crm/include/MVC/Controller/SugarController.php(466): SugarController->handle_action()\n#3 /var/www/html/crm/include/MVC/Controller/SugarController.php(361): SugarController->process()\n#4 /var/www/html/crm/include/MVC/SugarApplication.php(112): SugarController->execute()\n#5 /var/www/html/crm/index.php(52): SugarApplication->execute()\n#6 {main}\n  thrown in /var/www/html/crm/include/MVC/Controller/SugarController.php on line 649, referer: https://localhost/crm/index.php?module=master_shift&action=EditView&return_module=master_shift&return_action=DetailView
[/b]

#### Context
According to me, this issue is a high priority Because my custom module is depended on time-wise data.

#### Your Environment
* SuiteCRM Version used: 7.11.7

**Comment by kishah2411** [comment]
Hi Everyone,

Anyone have a solution related to this issue.
Please give me an update.

**Comment by Alhimeg** [comment]
Remove the ampersand sign from the second parameter in function save() in include/SugarFields/Fields/Time/SugarFieldTime.php line 89.

Like this
public function save(&$bean, $inputData, &$field, &$def, $prefix = '')

**Comment by pgorod** [comment]
Can both of you please test my PR #8519 for this Issue, and confirm if it works? Thank you!
