### ISSUE TITLE
Feature Request: Relate Workflow-Sent Emails to Contact

### ISSUE THREAD

**Issue by deuks** [salesagility/SuiteCRM#8214]
#### Issue
When sending emails using workflow, the emails that are sent to the contact are not related to the contact.

#### Expected Behavior
I feel that emails should at least have the option to be related to the contact when sent via workflow. 

#### Actual Behavior
For example, I created a workflow that sends a follow up email when a task's due date has passed.  It sends it to a "Related Field": "Contact:Contact Name"

This all works as expected, and while when you go to the contact's history subpanel the email is listed, the email is not actually related to the contact. It is merely there because SuiteCRM automatically places an email in a contact's history if the sent email address matches one of the contact's emails addresses. 

This is good, but what if the contact changes their email address? Or goes to a new company and therefore gets a new email address? Removing the email address from the Contact would then mean the email will disappear as well.  The only other way of relating it to the contact is manually, which I was trying to avoid by having workflow send the email.

#### Possible Fix
I don't know how feasible this is, but I can't imagine it is impossible to relate an email to a contact when you are selecting that contact bean to obtain their email address.  At some point in that process you have the contact's uuid, it would simply be a matter of passing that uuid to the email record when it is inserted to the email table.  

#### Steps to Reproduce
1. Create workflow with send email action
2. Set "To" to Related Field and then Contact:Contact Name
3. Trigger workflow
4. Check Contact's History Subpanel to see lack of relation.

**Comment by Mac-Rae** [comment]
Hi @deuks,

Can you confirm for me the email is being sent?, this is the error I get when attempting to replicate and no emails are sent

```
PHP Fatal error:  Uncaught Error: Call to a member function getPrimaryAddress() on null in /var/www/crm/myfork/modules/AOW_Actions/actions/actionSendEmail.php:298
Stack trace:
#0 /var/www/crm/myfork/modules/AOW_Actions/actions/actionSendEmail.php(335): actionSendEmail->getEmailsFromParams(Object(Task), Array)
#1 /var/www/crm/myfork/modules/AOW_WorkFlow/AOW_WorkFlow.php(962): actionSendEmail->run_action(Object(Task), Array, false)
#2 /var/www/crm/myfork/modules/AOW_WorkFlow/AOW_WorkFlow.php(210): AOW_WorkFlow->run_actions(Object(Task))
#3 /var/www/crm/myfork/modules/AOW_WorkFlow/AOW_WorkFlow.php(195): AOW_WorkFlow->run_flow()
#4 /var/www/crm/myfork/modules/Schedulers/_AddJobsHere.php(811): AOW_WorkFlow->run_flows()
#5 /var/www/crm/myfork/modules/SchedulersJobs/SchedulersJob.php(540): processAOW_Workflow(Object(SchedulersJob))
#6 /var/www/crm/myfork/include/SugarQueue/SugarCronJobs.php(191): SchedulersJob->runJob()
#7 /var/www/crm/myfork/include/SugarQueue/SugarCronJobs.php(231): SugarCronJobs->executeJob(Object(SchedulersJob))
 in /var/www/crm/myfork/modules/AOW_Actions/actions/actionSendEmail.php on line 298

````

**Comment by deuks** [comment]
Yes emails are sending. Like the title says this is not a issue but a feature request.  

I believe everything is working as intended.  Workflow sends the email and because the workflow module is "Task" in my case, the email is related to the task.  

I just think it would be nice if you could manually relate the email to the task's contact instead, kind of like how it works for every other record/module type. I'm on version 7.10.x so maybe this feature does exist in 7.11?

**Comment by Mac-Rae** [comment]
Whoops @deuks,

My mistake, managed to get this working during retesting. Will mark this as a suggestion :+1:
