### ISSUE TITLE
Oauth not working in suitecrm 7.11.10

### ISSUE THREAD

**Issue by ganesh-at-wiw** [salesagility/SuiteCRM#8406]
# Oauth not working in suitecrm 7.11.10

#### Issue
We upgraded suitecrm from 7.2. to 7.11.10.
Till we started from 7.2 version, everything was working fine.
After latest upgrade, We're facing below log entry whenever we're trying to do oauth which results in error in the app. The app using oauth from suitecrm is Quoteroller.

#### Expected Behavior
Working of oauth flawlessly.

#### Actual Behavior
Instead the log generated is:
```
[Wed Dec 25 11:36:24.730796 2019] [php7:error] [pid xxxx] [client xxxx:xxxx] PHP Fatal error:  Uncaught Error: Class 'SuiteCRM\\Zend_Uri_Http' not found in /var/www/html/crm/include/Zend_Oauth_Provider.php:266\nStack trace:\n#0 /var/www/html/crm/include/Zend_Oauth_Provider.php(288): SuiteCRM\\Zend_Oauth_Provider->getRequestUrl()\n#1 /var/www/html/crm/include/SugarOAuthServer.php(175): SuiteCRM\\Zend_Oauth_Provider->checkOAuthRequest(NULL, Array)\n#2 /var/www/html/crm/service/v4/SugarWebServiceUtilv4.php(489): SugarOAuthServer->__construct()\n#3 /var/www/html/crm/service/v4/SugarWebServiceUtilv4.php(477): SugarWebServiceUtilv4->checkOAuthAccess(Object(SoapError))\n#4 /var/www/html/crm/service/v4/SugarWebServiceImplv4.php(672): SugarWebServiceUtilv4->checkSessionAndModuleAccess(NULL, 'invalid_session', '', '', '', Object(SoapError))\n#5 /var/www/html/crm/service/core/REST/SugarRestJSON.php(94): SugarWebServiceImplv4->oauth_access(NULL)\n#6 /var/www/html/crm/service/core/SugarRestService.php(136): SugarRestJSON->serve()\n#7 /var/www/html/crm/service/core/webservice.php(69): SugarRestService->serve()\n#8 /var/www/html/ in /var/www/html/crm/include/Zend_Oauth_Provider.php on line 266
```
as per /var/log/apache2/error.log.

#### Possible Fix
Seems like fix is related to #7672, but couldn't get anything working yet.

#### Steps to Reproduce
1. We're using quoteroller.com's integration for suitecrm. Click on Opportunities-->View Opportunities-->Choose any opportunity--->Actions---> Create a Quote.
2. This is when the error happens as per log file entry provided above.

#### Context
We're trying to create quotes for clients through this integration.

#### Your Environment
* SuiteCRM Version used: 7.11.10
* Browser name and version: Firefox 71.0
* Environment name and version (e.g. MySQL, PHP 7): Mysql 5.7.28, PHP 7.3.13
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.

**Comment by Dillon-Brown** [comment]
Hi @ganesh-at-wiw, I've pushed up a potential fix for this here: #8409. Let me know if you encounter any issues.
