### ISSUE TITLE
SAML2 not passing username properly.

### ISSUE THREAD

**Issue by cbitterfield** [salesagility/SuiteCRM#8407]
#### Issue

Configuration for SAML assertion is not well documented.
I am using JumpCloud SSO (which has a configuration for SugarCRM).

I assume that auto-provision is not available. I have created a user in the SuiteCRM side.

[JumpCloud Support Doc]([https://support.jumpcloud.com/support/s/article/configuring-user-attributes-for-saml-connectors-2019-08-21-10-36-47#Configuring%20User%20Attributes]))

[SugarCRM Support Doc](https://support.sugarcrm.com/Knowledge_Base/Password_Management/Configuring_SAML_Attribute_Mapping_for_SugarIdentity/)

#### Actual Behavior
End Result is I get a blank browser.
The Logs don't show the attributes passed or if there is an encryption key issue

I get a lot of errors regarding Elastic Search. My server is too small to support the ES requirements. 

#### Possible Fix

Publish correct Mappings would certiainly help

#### Steps to Reproduce
See written article
![Screen Shot 2019-12-25 at 7 38 14 PM](https://user-images.githubusercontent.com/11802951/71456623-2bdc9f00-274f-11ea-85b5-8c3fcccf07fe.png)
![Screen Shot 2019-12-25 at 7 37 47 PM](https://user-images.githubusercontent.com/11802951/71456624-2bdc9f00-274f-11ea-98b0-8e0503d180d2.png)

#### Your Environment

* SuiteCRM Version used: 7.11.10
* Browser name and version: 71.0 (64-bit) [ Also tried chrome]
* Environment name and version: 
Apache 2
Percona MySQL 5.7
PHP 7.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 18.04

[*I am writing an article on this installation*](https://medium.com/@cbitterfield/installing-suitecrm-in-the-cloud-23c2a9e8c611)
All of my steps are document in this draft. When I get it working it will be public and I will contribute it to the community docs.

`Thu Dec 26 03:31:05 2019 [13872][1][DEBUG] setting cookie ck_login_id_20 to 1
Thu Dec 26 03:31:05 2019 [13872][1][DEBUG] setting cookie ck_login_language_20 to en_us
Thu Dec 26 03:31:11 2019 [13869][-none-][DEBUG] Hook called: Users::before_login
Thu Dec 26 03:31:11 2019 [13869][-none-][DEBUG] Hook called: Users::login_failed
Thu Dec 26 03:31:11 2019 [13869][-none-][FATAL] FAILED LOGIN:attempts[1], ip[73.71.239.163], username[]
Thu Dec 26 03:31:11 2019 [13869][-none-][DEBUG] Unable to find SugarController:: Login
Thu Dec 26 03:31:11 2019 [13869][-none-][DEBUG] Module:Users using file: Login
#0 /data/suitecrm/html/vendor/onelogin/php-saml/src/Saml2/Auth.php(177): OneLogin\Saml2\Settings->__construct(Array)
#1 /data/suitecrm/html/modules/Users/authentication/SAML2Authenticate/SAML2Authenticate.php(95): OneLogin\Saml2\Auth->__construct(Array)
#2 /data/suitecrm/html/modules/Users/Login.php(46): SAML2Authenticate->pre_login()
Thu Dec 26 03:31:13 2019 [13867][-none-][DEBUG] Unable to find SugarController:: Login
Thu Dec 26 03:31:13 2019 [13867][-none-][DEBUG] Module:Users using file: Login
#0 /data/suitecrm/html/vendor/onelogin/php-saml/src/Saml2/Auth.php(177): OneLogin\Saml2\Settings->__construct(Array)
#1 /data/suitecrm/html/modules/Users/authentication/SAML2Authenticate/SAML2Authenticate.php(95): OneLogin\Saml2\Auth->__construct(Array)
#2 /data/suitecrm/html/modules/Users/Login.php(46): SAML2Authenticate->pre_login()
Thu Dec 26 03:31:38 2019 [13715][1][DEBUG] setting cookie ck_login_id_20 to 1`

**Comment by samus-aran** [comment]
Hey @cbitterfield 

Thanks for your detailed bug report.  

Could be a couple of things different in your setup of SAML but lets work together to resolve which one is stopping you from logging in.

Since SugarCRM & SuiteCRM are now different (subtlely but still is) one thing is the same that you do need to ensure your CRM user's username is their email address e.g. username = abc@example.com 

Another point, which was a fairly recent implementation documented here about the default settings of the 3.3.x Saml library:
https://github.com/salesagility/SuiteCRM/pull/6850#issuecomment-555936024

Let us know how you get on.

**Comment by samus-aran** [comment]
Also on the Elastic Search you can spin it up with only using the required amount you need, we usually set up small implementations to 2GB.

**Comment by cbitterfield** [comment]
The server we are using is a 1GB RAM, 1vCPU machine. performance is good for the main application minus the error messages of Elastic Search. I installed elastic search 5.6, however, it was showing an 8GB minimum ram requirement. I'd rather not upgrade and redo the server. Is there any way to make ES work with 1GB RAM?

**Comment by cbitterfield** [comment]
That did not help:
Sat Dec 28 00:56:37 2019 [3394][-none-][DEBUG] Hook called: Users::before_login
Sat Dec 28 00:56:37 2019 [3394][-none-][DEBUG] Hook called: Users::login_failed
Sat Dec 28 00:56:37 2019 [3394][-none-][FATAL] FAILED LOGIN:attempts[1], ip[73.71.239.163], username[]
Sat Dec 28 00:56:37 2019 [3394][-none-][DEBUG] Unable to find SugarController:: Login
Sat Dec 28 00:56:37 2019 [3394][-none-][DEBUG] Module:Users using file: Login
Sat Dec 28 00:56:40 2019 [3394][-none-][DEBUG] Unable to find SugarController:: Login
Sat Dec 28 00:56:40 2019 [3394][-none-][DEBUG] Module:Users using file: Login

The main login screen says: You must specify a valid username and password.

email address is set as a username.

**Comment by samus-aran** [comment]
Hey @cbitterfield ,

There are a few things we could try:

1. You need to also update the User Profile to use external auth login which is on the Advanced tab on the user. If you can't access it now (since you can't login via SAML) you can update in the database field "external_auth_only" to true

2. After this has been done also try the following out:

https://github.com/salesagility/SuiteCRM/blob/ef1b41965c056937894dd3018d3b149c9c25a9a9/modules/Users/authentication/SAML2Authenticate/SAML2AuthenticateUser.php#L69

Change this line to the below:

`if (empty($row) || $row['external_auth_only'] === 1) {
        return '';
    }`

Let us know how you get on.

**Comment by Mac-Rae** [comment]
Hi @cbitterfield,

Is this still an issue?, Nice article btw :+1:

**Comment by cbitterfield** [comment]
I never got it working. I just got distracted. I will get back to it soon.

**Comment by tsmgeek** [comment]
https://github.com/salesagility/SuiteCRM/pull/8996

Im proposing change to allow full override of the onelogin settings file, if you set 'onelogin' in config you define it exactly as per the library array, what you see in the UI is ignored.
