### ISSUE TITLE
System upgrade fails after upgrading to 7.10.25

### ISSUE THREAD

**Issue by aimran50** [salesagility/SuiteCRM#8637]
Upgraded from 7.8.30 to 7.10.25. Performed repairs.

Now clicking on upgrade results in a blank screen.

#### Issue

Apache error.log shows this:
[Mon Mar 30 13:30:18.308646 2020] [php7:notice] [pid 37912:tid 1400] [client ::1:56139] PHP Notice:  Undefined index: email_warning_notifications in C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\Administration\\Administration.php on line 84, referer: http://localhost/crm/index.php?module=Emails&action=index&return_module=Emails&return_action=DetailView
[Mon Mar 30 13:30:21.452761 2020] [php7:notice] [pid 37912:tid 1400] [client ::1:56139] PHP Notice:  Undefined index: email_warning_notifications in C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\Administration\\Administration.php on line 84, referer: http://localhost/crm/index.php?module=AOR_Reports&action=index&parentTab=All
[Mon Mar 30 13:30:35.123808 2020] [php7:notice] [pid 37912:tid 1420] [client ::1:56154] PHP Notice:  Undefined index: email_warning_notifications in C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\Administration\\Administration.php on line 84, referer: http://localhost/crm/index.php?module=AOR_Reports&offset=4&stamp=1585593018058087400&return_module=AOR_Reports&action=DetailView&record=6bf2c406-19ff-0b1e-cdcf-5e7bf16ab987
[Mon Mar 30 13:30:43.013877 2020] [php7:notice] [pid 37912:tid 1420] [client ::1:56158] PHP Notice:  Undefined index: email_warning_notifications in C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\Administration\\Administration.php on line 84, referer: http://localhost/crm/index.php?module=Administration&action=index
[Mon Mar 30 13:30:43.033913 2020] [php7:notice] [pid 37912:tid 1420] [client ::1:56158] PHP Notice:  Undefined index: additional_step in C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\UpgradeWizard\\index.php on line 291, referer: http://localhost/crm/index.php?module=Administration&action=index
[Mon Mar 30 13:30:45.732172 2020] [php7:notice] [pid 37912:tid 1420] [client ::1:56158] PHP Notice:  Undefined index: email_warning_notifications in C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\Administration\\Administration.php on line 84, referer: http://localhost/crm/index.php?module=UpgradeWizard&action=index
[Mon Mar 30 13:30:45.739133 2020] [php7:notice] [pid 37912:tid 1420] [client ::1:56158] PHP Notice:  Undefined index: additional_step in C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\UpgradeWizard\\index.php on line 291, referer: http://localhost/crm/index.php?module=UpgradeWizard&action=index
[Mon Mar 30 13:30:45.749170 2020] [php7:error] [pid 37912:tid 1420] [client ::1:56158] PHP Fatal error:  Uncaught Error: Cannot use object of type SplFileInfo as array in C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\include\\utils\\file_utils.php:57\nStack trace:\n#0 C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\UpgradeWizard\\uw_utils.php(4579): clean_path(Object(SplFileInfo))\n#1 C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\UpgradeWizard\\systemCheck.php(83): dirInArray(Object(SplFileInfo), Array)\n#2 C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\UpgradeWizard\\index.php(292): require('C:\\\\Bitnami\\\\wamp...')\n#3 C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\include\\MVC\\View\\SugarView.php(818): include_once('C:\\\\Bitnami\\\\wamp...')\n#4 C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\include\\MVC\\View\\views\\view.classic.php(72): SugarView->includeClassicFile(Object(SplFileInfo))\n#5 C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\include\\MVC\\View\\SugarView.php(211): ViewClassic->display()\n#6 C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\include\\MVC\\Controller\\Sugar in C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\include\\utils\\file_utils.php on line 57, referer: http://localhost/crm/index.php?module=UpgradeWizard&action=index
[Mon Mar 30 13:31:00.145837 2020] [php7:notice] [pid 37912:tid 1420] [client ::1:56176] PHP Notice:  Undefined index: email_warning_notifications in C:\\Bitnami\\wampstack-7.1.33-0\\apps\\suitecrm\\htdocs\\modules\\Administration\\Administration.php on line 84, referer: http://localhost/crm/index.php

#### Expected Behavior

Upgrade should proceed.

#### Actual Behavior

A blank screen is displayed.

#### Steps to Reproduce

1. Upgrade from 7.8.30 to 7.10.25 wiht package provided on the upgrade page.
2. Perform repairs
3. Click on upgrade again and click next
4. Blank screen is diaplayed

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment]
What is your version of PHP?

**Comment by pgorod** [comment]
Can you please try this change to see if it fixes the issue for you on Windows? Tell me how it goes.

Thanks.

**Comment by pgorod** [comment]
Just so I understand, this can only happen when you restart the upgrade, but there is no reason for you to restart the upgrade, is there? You are already on the latest version.

You were just trying out the Upgrade Wizard and found this bug, right?

This is relevant to check my assessment of the severity of the bug, which goes like this:

1. The bug is in the 7.10.25 and 7.11.13 packages
1. Affects Windows only
1. BUT people upgrading TO those packages, won't see the bug, because the code that will run for the system check is still the old one
1. ONLY people who restart the upgrade due to an interruption, or for no reason at all, just trying out the upgrade wizard, will see the bug (and hopefully can fix it with my fix above)
1. People on Windows who used these packages, WILL see the bug in their next upgrade, even if we put the fix into future packages 

So I don't think this is a problem for now, but will be in the next upgrade, so to mitigate we should confirm the fix works and put it into the current packages as soon as possible. The less people install this now on Windows with the buggy code, the better the next release cycle will go.
