### ISSUE TITLE
PHP Fatal error while installing from hotfix-7.10.x branch

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#8688]
#### Issue

While installing from branch hotfix-7.10.x I get the following `PHP Fatal error`:

![imagen](https://user-images.githubusercontent.com/939888/80745144-37bde080-8af6-11ea-98d1-a0b0c4c645f7.png)

In suitecrm.log I can see:

```log
Thu Apr 30 15:18:26 2020 [19342][-none-][FATAL] SugarBean::populateDefaultValues $field_defs should be an array
Thu Apr 30 15:18:26 2020 [19342][-none-][FATAL] "name" field does not exists in field definition.
Thu Apr 30 15:18:26 2020 [19342][-none-][FATAL] Mysqli_query failed.
Thu Apr 30 15:18:26 2020 [19342][-none-][FATAL] Error creating table: : Query Failed: CREATE TABLE  (   NULL  ) CHARACTER SET utf8 COLLATE utf8_general_ci: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(   NULL  ) CHARACTER SET utf8 COLLATE utf8_general_ci' at line 1
```
and in PHP log I can see:

```bash
[Thu Apr 30 15:18:16 2020] 127.0.0.1:44758 [200]: /install.php
[Thu Apr 30 15:18:26 2020] PHP Notice:  Undefined variable: colBaseType in /home/jose/trabajos/SuiteCRM/include/database/DBManager.php on line 2635
[Thu Apr 30 15:18:26 2020] PHP Stack trace:
[Thu Apr 30 15:18:26 2020] PHP   1. {main}() /home/jose/trabajos/SuiteCRM/install.php:0
[Thu Apr 30 15:18:26 2020] PHP   2. require() /home/jose/trabajos/SuiteCRM/install.php:793
[Thu Apr 30 15:18:26 2020] PHP   3. create_table_if_not_exist() /home/jose/trabajos/SuiteCRM/install/performSetup.php:281
[Thu Apr 30 15:18:26 2020] PHP   4. Audit->create_tables() /home/jose/trabajos/SuiteCRM/install/install_utils.php:1274
[Thu Apr 30 15:18:26 2020] PHP   5. MysqliManager->createTable() /home/jose/trabajos/SuiteCRM/data/SugarBean.php:2171
[Thu Apr 30 15:18:26 2020] PHP   6. MysqliManager->createTableSQL() /home/jose/trabajos/SuiteCRM/include/database/DBManager.php:673
[Thu Apr 30 15:18:26 2020] PHP   7. MysqliManager->createTableSQLParams() /home/jose/trabajos/SuiteCRM/include/database/MysqlManager.php:757
[Thu Apr 30 15:18:26 2020] PHP   8. MysqliManager->columnSQLRep() /home/jose/trabajos/SuiteCRM/include/database/MysqlManager.php:778
[Thu Apr 30 15:18:26 2020] PHP   9. MysqliManager->oneColumnSQLRep() /home/jose/trabajos/SuiteCRM/include/database/DBManager.php:2713
[Thu Apr 30 15:18:26 2020] PHP  10. MysqliManager->oneColumnSQLRep() /home/jose/trabajos/SuiteCRM/include/database/MysqlManager.php:818
[Thu Apr 30 15:18:26 2020] PHP Notice:  Undefined variable: colBaseType in /home/jose/trabajos/SuiteCRM/include/database/DBManager.php on line 2678
[Thu Apr 30 15:18:26 2020] PHP Stack trace:
[Thu Apr 30 15:18:26 2020] PHP   1. {main}() /home/jose/trabajos/SuiteCRM/install.php:0
[Thu Apr 30 15:18:26 2020] PHP   2. require() /home/jose/trabajos/SuiteCRM/install.php:793
[Thu Apr 30 15:18:26 2020] PHP   3. create_table_if_not_exist() /home/jose/trabajos/SuiteCRM/install/performSetup.php:281
[Thu Apr 30 15:18:26 2020] PHP   4. Audit->create_tables() /home/jose/trabajos/SuiteCRM/install/install_utils.php:1274
[Thu Apr 30 15:18:26 2020] PHP   5. MysqliManager->createTable() /home/jose/trabajos/SuiteCRM/data/SugarBean.php:2171
[Thu Apr 30 15:18:26 2020] PHP   6. MysqliManager->createTableSQL() /home/jose/trabajos/SuiteCRM/include/database/DBManager.php:673
[Thu Apr 30 15:18:26 2020] PHP   7. MysqliManager->createTableSQLParams() /home/jose/trabajos/SuiteCRM/include/database/MysqlManager.php:757
[Thu Apr 30 15:18:26 2020] PHP   8. MysqliManager->columnSQLRep() /home/jose/trabajos/SuiteCRM/include/database/MysqlManager.php:778
[Thu Apr 30 15:18:26 2020] PHP   9. MysqliManager->oneColumnSQLRep() /home/jose/trabajos/SuiteCRM/include/database/DBManager.php:2713
[Thu Apr 30 15:18:26 2020] PHP  10. MysqliManager->oneColumnSQLRep() /home/jose/trabajos/SuiteCRM/include/database/MysqlManager.php:818
[Thu Apr 30 15:18:26 2020] PHP Fatal error:  Uncaught Exception: Database error. Please check suitecrm.log for details. in /home/jose/trabajos/SuiteCRM/include/utils.php:1881
Stack trace:
#0 /home/jose/trabajos/SuiteCRM/include/database/DBManager.php(355): sugar_die('Database error....')
#1 /home/jose/trabajos/SuiteCRM/include/database/DBManager.php(328): DBManager->registerError('Error creating ...', 'Error creating ...', true)
#2 /home/jose/trabajos/SuiteCRM/include/database/MysqliManager.php(179): DBManager->checkError('Error creating ...', true)
#3 /home/jose/trabajos/SuiteCRM/include/database/DBManager.php(676): MysqliManager->query('CREATE TABLE  (...', true, 'Error creating ...')
#4 /home/jose/trabajos/SuiteCRM/data/SugarBean.php(2171): DBManager->createTable(Object(Audit))
#5 /home/jose/trabajos/SuiteCRM/install/install_utils.php(1274): SugarBean->create_tables()
#6 /home/jose/trabajos/SuiteCRM/install/performSetup.php(281): create_table_if_not_exist(Object(Audit))
#7 /home/jose/trabajos/SuiteCRM/install.php(793): require('/home/jose/trab...')
# in /home/jose/trabajos/SuiteCRM/include/utils.php on line 1881
[Thu Apr 30 15:18:26 2020] 127.0.0.1:44762 [500]: /install.php - Uncaught Exception: Database error. Please check suitecrm.log for details. in /home/jose/trabajos/SuiteCRM/include/utils.php:1881
Stack trace:
#0 /home/jose/trabajos/SuiteCRM/include/database/DBManager.php(355): sugar_die('Database error....')
#1 /home/jose/trabajos/SuiteCRM/include/database/DBManager.php(328): DBManager->registerError('Error creating ...', 'Error creating ...', true)
#2 /home/jose/trabajos/SuiteCRM/include/database/MysqliManager.php(179): DBManager->checkError('Error creating ...', true)
#3 /home/jose/trabajos/SuiteCRM/include/database/DBManager.php(676): MysqliManager->query('CREATE TABLE  (...', true, 'Error creating ...')
#4 /home/jose/trabajos/SuiteCRM/data/SugarBean.php(2171): DBManager->createTable(Object(Audit))
#5 /home/jose/trabajos/SuiteCRM/install/install_utils.php(1274): SugarBean->create_tables()
#6 /home/jose/trabajos/SuiteCRM/install/performSetup.php(281): create_table_if_not_exist(Object(Audit))
#7 /home/jose/trabajos/SuiteCRM/install.php(793): require('/home/jose/trab...')
# in /home/jose/trabajos/SuiteCRM/include/utils.php on line 1881
[Thu Apr 30 15:18:26 2020] 127.0.0.1:44768 [200]: /install/status.json?0.4984184699407993
```

#### Expected Behavior

SuiteCRM installs without problems

#### Actual Behavior

The installation process stops

#### Steps to Reproduce

1. Clone SuiteCRM  repo
2. change to hotfix-7.10.x branch
3. run compose install
4. Run the install process from the browser

#### Your Environment

* SuiteCRM Version used: 7.10.x
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 75
* Environment name and version (e.g. MySQL, PHP 7): MySQL 8.0 / PHP 7.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 19.10

**Comment by novastream** [comment]
I have the same issue on a fresh install of SuiteCRM (7.11.15)

**Expected Behavior**
SuiteCRM installs without problems

**Actual Behavior**
The installation process stops

**Possible Fix**

**Steps to Reproduce**
Download latest release
Upload to server
Run install process from the browser

**Context**

**Your Environment**
SuiteCRM Version used: 7.11.15
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 81.0.1 and Brave 1.14.44
Environment name and version (e.g. MySQL, PHP 7): nginx / MySQL 8.0.19 / PHP 7.2
Operating System and version (e.g Ubuntu 16.04): Ubuntu 20.04 LTS

[suitecrm.log](https://github.com/salesagility/SuiteCRM/files/5377203/suitecrm.log)

**Comment by pgorod** [comment]
This is caused by using MySQL 8.0 which is not supported yet.
