### ISSUE TITLE
Fatal Error and Uncaught Exception during install

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteCRM#8786]
#### Issue

If in a non installed instance of SuiteCRM you go to `index.php` you will be re-directed to the installation page: `install.php` That's great, but in the log you will have an `Uncaught Exception`:

```bash
[Fri Jun 19 14:48:05 2020] PHP Fatal error:  Uncaught Exception: SuiteCRM is not installed. Entry point needs an installed SuiteCRM, please install first. in /home/jose/trabajos/SuiteCRM/include/entryPoint.php:59
Stack trace:
#0 /home/jose/trabajos/SuiteCRM/index.php(47): require_once()
#1 {main}
  thrown in /home/jose/trabajos/SuiteCRM/include/entryPoint.php on line 59
[Fri Jun 19 14:48:05 2020] 127.0.0.1:45778 [302]: GET / - Uncaught Exception: SuiteCRM is not installed. Entry point needs an installed SuiteCRM, please install first. in /home/jose/trabajos/SuiteCRM/include/entryPoint.php:59
Stack trace:
#0 /home/jose/trabajos/SuiteCRM/index.php(47): require_once()
#1 {main}
  thrown in /home/jose/trabajos/SuiteCRM/include/entryPoint.php on line 59
```

#### Expected Behavior

No `Fatal Errors` and `Uncaught Exceptions` in PHP log ;-)

#### Actual Behavior

We have an ugly `Fatal Error` and `Uncaught Exception`  in PHP log

#### Possible Fix

The code that throws the exception is in `include/entryPoint.php`:

```php
if (empty($GLOBALS['installing']) && !file_exists('config.php')) {
    header('Location: install.php');
    throw new Exception('SuiteCRM is not installed. Entry point needs an installed SuiteCRM, please install first.');
}
```
This exception is thrown after a `header()` so execution continues on its way redirecting you to the installation, so the message in the exception `"SuiteCRM is not installed. Entry point needs an installed SuiteCRM, please install first."` is useless, so may be we can remove that line:

```php
if (empty($GLOBALS['installing']) && !file_exists('config.php')) {
    header('Location: install.php');
}
```

#### Steps to Reproduce

1. Open the browser in `index.php` in a non installed SuiteCRM instance
2. See PHP log ;-)

#### Your Environment

* SuiteCRM Version used: 7.10.27
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 77
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.3 - MySQL 8.0.x
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 20.04

**Comment by chris001** [comment]
You're right.  `"Not installed yet"` is a normal condition, so it should log something to register that it detected this.  It should throw Exception when install fails in some way.
