### ISSUE TITLE
Fatal Error - LoggerManager not found in sugar_file_utils.php

### ISSUE THREAD

**Issue by tsmgeek** [salesagility/SuiteCRM#8802]
Getting this error, not sure why as LoggerManager should be required in entryPoint.php

https://github.com/salesagility/SuiteCRM/blob/master/include/utils/sugar_file_utils.php#L158

```
[Thu Jul 02 10:15:02.423549 2020] [php7:error] [pid 5574] [client 10.100.116.47:54406] PHP Fatal error:  Uncaught Error: Class 'LoggerManager' not found in /var/www/html/include/utils/sugar_file_utils.php:157\nStack trace:\n#0 /var/www/html/include/SugarTheme/SugarTheme.php(429): sugar_file_put_contents('cache/themes/Su...', 'a:4:{s:7:"jsCac...')\n#1 [internal function]: SugarTheme->__destruct()\n#2 {main}\n  thrown in /var/www/html/include/utils/sugar_file_utils.php on line 157, referer: http://localhost/index.php?module=Emails&action=ComposeView&return_module=Emails&return_action=index
````

SuiteCRM 7.10.27

**Comment by pgorod** [comment]
With line breaks...
```
[Thu Jul 02 10:15:02.423549 2020] [php7:error] [pid 5574] [client 10.100.116.47:54406] 
PHP Fatal error:  Uncaught Error: Class 'LoggerManager' not found in 
/var/www/html/include/utils/sugar_file_utils.php:157
Stack trace:

#0 /var/www/html/include/SugarTheme/SugarTheme.php(429): sugar_file_put_contents('cache/themes/Su...', 'a:4:{s:7:"jsCac...')
#1 [internal function]: SugarTheme->__destruct()
#2 {main}

thrown in /var/www/html/include/utils/sugar_file_utils.php on line 157, referer: http://localhost/index.php?module=Emails&action=ComposeView&return_module=Emails&return_action=index
```

**Comment by tsmgeek** [comment]
I think this is related to `entryPoint=getImage`. Ile just write the flow

- index.php
- require - include/MVC/preDispatch.php
- if entryPoint = getImage -> SugarTheme 
- SugarTheme `_destruct` calls `sugar_file_put_contents`

Logger is only loaded in the `include/entryPoint.php` file which is after the preDispatch code.
Maybe the logger needs to be loaded earlier or there is an `init.php` that always happens before everything else with minimum code needed across everything.
