### ISSUE TITLE
An error appears when emptying a date field from an inline function

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#8971]
An Internal Server Error appears when trying to leave empty a date field using the inline-edit function in the DetailView or ListView of any module. Refreshing the page after the error shows the field empty, as expected.

The PHP error is:

`
[Tue Nov 24 10:40:21.232306 2020] [proxy_fcgi:error] [pid 28540:tid 140093260900096] [client 81.37.236.170:50584] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function format() on bool in /xxxxxxx/include/InlineEditing/InlineEditing.php:437\nStack trace:\n#0 /xxxxxxx/include/InlineEditing/InlineEditing.php(391): formatDisplayValue(Object(Contact), '', Array, 'save')\n#1 /xxxxxxxxx/include/InlineEditing/InlineEditing.php(372): getDisplayValue(Object(Contact), 'birthdate')\n#2 /xxxxxx/modules/Home/controller.php(60): saveField('birthdate', '7ad03f24-2a3b-7...', 'Contacts', '', 'index')\n#3 /xxxxxx/include/MVC/Controller/SugarController.php(525): HomeController->action_saveHTMLField()\n#4 /xxxxxx/include/MVC/Controller/SugarController.php(494): SugarController->do_action()\n#5 /xxxxxxx/include/MVC/Controller/SugarController.php(468): SugarController->handle_action()...', referer: https://xxxxx/index.php?action=ajaxui
`

#### Issue
If a date field has some value, an the user wants to leave it empty using the inline-edit function, an Internal Server Error is thrown.

#### Expected Behavior
After deleting the value, the field should appear empty without throwing an error.

#### Actual Behavior
An internal server error appears:

![image](https://user-images.githubusercontent.com/61022311/100077852-25651480-2e43-11eb-8dad-22f21c2de08d.png)

#### Possible Fix
--

#### Steps to Reproduce
1. Go to the Contacts module in Studio
2. Add the field birthdate to the ListView
3. Go to the ListView of Contacts and add some value to the field birthdate of any record
4. Using the inline-function, remove the value of the field and submit.
5. The error should appear

#### Context
Although the value appears correctly after refresh, the error shouldn't appear

#### Your Environment
SuiteCRM Version used: 7.11.15 and 18 (and SugarCRM 6.5)
Browser name and version: Chrome 83.0.4103 and Firefox 77.0.1 (64-bit)
Environment name and version: PHP 7.3, MySQL
Operating System and version: Debian 9

**Comment by SinergiaCRM** [comment]
Fixed for now
