### ISSUE TITLE
Quick Repair and Rebuild causes a database failure

### ISSUE THREAD

**Issue by dan286608** [salesagility/SuiteCRM#9130]
#### Your Environment:

* SuiteCRM Version used: 7.11.18
* Browser name and version: Chrome version 90.0.4430.212 (Official Build)(64-bit)
* Environment name and version: Microsoft SQL Server, PHP 7.3.26
* Operating System and version: Windows Server 2019 build 17763

Hello. I am running SuiteCRM version 7.11.18. Whenever I go to Repair/ Quick Repair and Rebuild I get a message that says "differences found between database and vardefs." I haven't done much with the software other than creating a few custom fields. When I try and execute the repair and rebuild I get a message that reads "Database failure. Please refer to suitecrm.log for details."
The log states:

```Mon May 17 12:19:10 2021 [10112][102e8427-045d-3645-c47c-600efa5c0522][FATAL] Executing repair query:  Query Failed:CREATE INDEX idx_user_name ON users (user_name,is_group,status,last_name (30),first_name (30),id)::: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '('.
Mon May 17 12:19:10 2021 [10112][102e8427-045d-3645-c47c-600efa5c0522][FATAL] Exception handling in C:\SuiteCRM\include\MVC\Controller\SugarController.php:400
Mon May 17 12:19:10 2021 [10112][102e8427-045d-3645-c47c-600efa5c0522][FATAL] Exception in Controller: Database failure. Please refer to suitecrm.log for details.
Mon May 17 12:19:10 2021 [10112][102e8427-045d-3645-c47c-600efa5c0522][FATAL] backtrace:
#0 C:\SuiteCRM\include\database\DBManager.php(353): sugar_die('Database failur...')
#1 C:\SuiteCRM\include\database\DBManager.php(328): DBManager->registerError('Executing repai...', 'Executing repai...', true)
#2 C:\SuiteCRM\include\database\SqlsrvManager.php(235): DBManager->checkError('Executing repai...', true)
#3 C:\SuiteCRM\modules\Administration\repairDatabase.php(97): SqlsrvManager->query('CREATE INDEX id...', true, 'Executing repai...')
#4 C:\SuiteCRM\include\MVC\View\SugarView.php(839): include_once('C:\\SuiteCRM\\mod...')
#5 C:\SuiteCRM\include\MVC\View\views\view.classic.php(72): SugarView->includeClassicFile('modules/Adminis...')
#6 C:\SuiteCRM\include\MVC\View\SugarView.php(226): ViewClassic->display()
#7 C:\SuiteCRM\include\MVC\Controller\SugarController.php(435): SugarView->process()
#8 C:\SuiteCRM\include\MVC\Controller\SugarController.php(375): SugarController->processView()
#9 C:\SuiteCRM\include\MVC\SugarApplication.php(113): SugarController->execute()
#10 C:\SuiteCRM\index.php(52): SugarApplication->execute()
#11 {main}```

If someone could help me out or point me in the right direction it would be much appreciated!

**Comment by chris001** [comment]
You should edit your post, add triple backtick ` ``` ` before the start, and after the end, of your log file lines!

**Comment by dan286608** [comment]
@chris001 Thanks for letting me know, I have gone ahead and done so.

**Comment by chris001** [comment]
Welcome, actually, I meant, one triple backtick before the start of the entire log, and one triple backtick at the end of the entire log.  How you have it right now appears to be triple backtick starting and ending each line?  Anyway it reads much better either way.

**Comment by pgorod** [comment]
@dan286608 you say it's MySQL but from the logs it appears to be Microsoft SQL Server... which is it?

And exactly which version?

Is it a new installation, or was this working well before?

**Comment by dan286608** [comment]
@pgorod It is Microsoft SQL server, my mistake. My company had SuiteCRM installed a while ago as we are replacing our extremely old CRM system. They got busy with other work and pushed the production off to the side. When I came on board I was given the task of updating SuiteCRM and now I have begun to customize it a bit with Studio. I only recently tried doing a rebuild/repair because I was searching for a way to add more than two columns when editing a module in Studio, and the method I found required me to change some code and rebuild/repair. Then I was greeted with that database error.

**Comment by johnM2401** [comment]
Hey, 

If you are still able to see it, could you perhaps pass over the SQL that is provided by the Quick Repair and Rebuild?
This might give some more insight into what is causing this issue

You also mentioned that you have made code changes, do you think these may be related to the Database Error?
It may be worth checking if you get the same Database error, when running Quick Repair and Rebuild, without these changes

**Comment by dan286608** [comment]
@johnM2401 I had only adjusted one line of code. Just for testing I reverted it back and still receive the database error. The SQL of the Quick Repair and Rebuild is below.

```/* Table : users */
/*COLUMNS*/
/* INDEXES */
/*MISSING INDEX IN DATABASE - idx_user_name -index  ROW */
CREATE INDEX idx_user_name ON users (user_name,is_group,status,last_name (30),first_name (30),id);;

/* Table : jjwg_maps */
/*COLUMNS*/
/*MISMATCH WITH DATABASE - distance -  ROW [name] => 'distance'  [type] => 'real'  [len] => '4'  */
/* VARDEF - distance -  ROW[required] => ''  [name] => 'distance'  [vname] => 'LBL_DISTANCE'  [type] => 'float'  [massupdate] => '0'  [comments] => ''  [help] => 'Distance'  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => '1'  [reportable] => '1'  [len] => '9,4'  [size] => '20'  [precision] => '4'  [dbType] => 'float'  [default] => ''  */
 ALTER TABLE jjwg_maps ALTER COLUMN [distance] float(9) NULL ;
 ;
/* INDEXES */
/* Table : jjwg_markers */
/*COLUMNS*/
/*MISMATCH WITH DATABASE - jjwg_maps_lat -  ROW [name] => 'jjwg_maps_lat'  [type] => 'real'  [len] => '4'  [default] => '0.00000000'  */
/* VARDEF - jjwg_maps_lat -  ROW[required] => ''  [name] => 'jjwg_maps_lat'  [vname] => 'LBL_JJWG_MAPS_LAT'  [type] => 'float'  [massupdate] => '0'  [default] => '0.00000000'  [comments] => ''  [help] => 'Latitude'  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => ''  [reportable] => '1'  [len] => '10,8'  [size] => '20'  [precision] => '8'  [dbType] => 'float'  */
 ALTER TABLE jjwg_markers DROP CONSTRAINT DF__jjwg_mark__jjwg___07AC1A97 ALTER TABLE jjwg_markers ALTER COLUMN [jjwg_maps_lat] float(10) NULL ;
 ALTER TABLE jjwg_markers ADD   DEFAULT '0.00000000' FOR jjwg_maps_lat ;
/*MISMATCH WITH DATABASE - jjwg_maps_lng -  ROW [name] => 'jjwg_maps_lng'  [type] => 'real'  [len] => '4'  [default] => '0.00000000'  */
/* VARDEF - jjwg_maps_lng -  ROW[required] => ''  [name] => 'jjwg_maps_lng'  [vname] => 'LBL_JJWG_MAPS_LNG'  [type] => 'float'  [massupdate] => '0'  [default] => '0.00000000'  [comments] => ''  [help] => 'Longitude'  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => ''  [reportable] => '1'  [len] => '11,8'  [size] => '20'  [precision] => '8'  [dbType] => 'float'  */
 ALTER TABLE jjwg_markers DROP CONSTRAINT DF__jjwg_mark__jjwg___08A03ED0 ALTER TABLE jjwg_markers ALTER COLUMN [jjwg_maps_lng] float(11) NULL ;
 ALTER TABLE jjwg_markers ADD   DEFAULT '0.00000000' FOR jjwg_maps_lng ;
/* INDEXES */
/* Table : jjwg_address_cache */
/*COLUMNS*/
/*MISMATCH WITH DATABASE - lat -  ROW [name] => 'lat'  [type] => 'real'  [len] => '4'  */
/* VARDEF - lat -  ROW[required] => ''  [name] => 'lat'  [vname] => 'LBL_LAT'  [type] => 'float'  [massupdate] => '0'  [comments] => ''  [help] => 'Latitude'  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => ''  [reportable] => '1'  [len] => '10,8'  [size] => '20'  [precision] => '8'  [dbType] => 'float'  [default] => ''  */
 ALTER TABLE jjwg_address_cache ALTER COLUMN [lat] float(10) NULL ;
 ;
/*MISMATCH WITH DATABASE - lng -  ROW [name] => 'lng'  [type] => 'real'  [len] => '4'  */
/* VARDEF - lng -  ROW[required] => ''  [name] => 'lng'  [vname] => 'LBL_LNG'  [type] => 'float'  [massupdate] => '0'  [comments] => ''  [help] => 'Longitude'  [importable] => 'true'  [duplicate_merge] => 'disabled'  [duplicate_merge_dom_value] => '0'  [audited] => ''  [reportable] => '1'  [len] => '11,8'  [size] => '20'  [precision] => '8'  [dbType] => 'float'  [default] => ''  */
 ALTER TABLE jjwg_address_cache ALTER COLUMN [lng] float(11) NULL ;
 ;
/* INDEXES */
/* Table : users_feeds */
/*COLUMNS*/
/*MISSING IN DATABASE - suite_rank -  ROW*/
 ALTER TABLE users_feeds ADD [suite_rank] int  NULL  ;
/* INDEXES */```

**Comment by pribeiro42** [comment]
@dan286608 Hi there, it seams that the "CREATE INDEX" statement is at fault here, I personally don't use SQL Server these days, but if I recall correctly, the correct statement shouln't have the width of the field, like so:
```sql
CREATE INDEX idx_user_name ON users (user_name, is_group, status, last_name, first_name, id);
```
Also, I recall that was some kind of issue with index creation in some versions of MySQL / MariaDB.. .not sure, though...

One possible way of getting rid of this is to delete the field widths in the index line and execute the SQL script.
Let us know how it went...

**Comment by dan286608** [comment]
@pribeiro42 That worked! Database table are now synced with vardefs. Thank you all for you help.

**Comment by chris001** [comment]
The true fix for this bug, is to update the MSSQL driver class, to automatically generate the correct SQL commands (in this case, for `CREATE INDEX`) which would be compatible with the MSSQL database running on the user's CRM instance (for this command, omitting the field widths)... for the most popular databases, or switch over to wrap a newer better database abstraction layer which already automatically does this!

**Comment by dan286608** [comment]
@chris001 Thank you for that information, I will work on getting that updated since it has been quite annoying to constantly keep deleting the widths every time I need to run a repair. By chance, do you know how the SQL is generated within the Quick repair and Rebuild?

**Comment by chris001** [comment]
@dan286608 The SQL is generated in the PHP code of the CRM application!  As you can see here:

* https://github.com/salesagility/SuiteCRM/search?p=2&q=quickrepairandrebuild
* https://github.com/salesagility/SuiteCRM/blob/master/modules/Administration/QuickRepairAndRebuild.php
* https://github.com/salesagility/SuiteCRM/blob/master/modules/Administration/repairDatabase.php

**Comment by serhiisamko091184** [comment]
Hello, @dan286608 

The issue has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii
