### ISSUE TITLE
Cannot make new OAuth password client: PHP Fatal error:  Uncaught TypeError: Unsupported operand types

### ISSUE THREAD

**Issue by mstyp** [salesagility/SuiteCRM#9374]
#### Issue

I cannot make new oauth password client. 

#### Expected Behavior

When I click "New Password Client", I should be able to set a new password client. 

#### Actual Behavior

If I have ajax enabled, I see: "There was an error processing your request, please try again at a later time"

When I disable ajax, I see a bunch of weird gibberish that starts with:

```
{* /** * * SugarCRM Community Edition is a customer relationship management program developed by * SugarCRM, Inc.....
```

When I check my error logs, I see that there is fatal php error:

```
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string % int in /var/www/html/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php:194\nStack trace:\n#0 /var/www/html/suitecrm/vendor/smarty/smarty/libs/Smarty.class.php(1875): include()\n#1 /var/www/html/suitecrm/include/Sugar_Smarty.php(168): Smarty->_smarty_include()\n#2 /var/www/html/suitecrm/cache/smarty/templates_c/%%07^072^072FA7F7%%EditView.tpl.php(260): Sugar_Smarty->_smarty_include()\n#3 /var/www/html/suitecrm/vendor/smarty/smarty/libs/Smarty.class.php(1269): include('...')\n#4 /var/www/html/suitecrm/include/Sugar_Smarty.php(151): Smarty->fetch()\n#5 /var/www/html/suitecrm/include/TemplateHandler/TemplateHandler.php(172): Sugar_Smarty->fetch()\n#6 /var/www/html/suitecrm/include/TemplateHandler/TemplateHandler.php(361): TemplateHandler->buildTemplate()\n#7 /var/www/html/suitecrm/include/EditView/EditView2.php(934): TemplateHandler->displayTemplate()\n#8 /var/www/html/suitecrm/include/MVC/View/vi...'
```

which looks similar to this issue: https://stackoverflow.com/questions/66238017/fatal-error-uncaught-typeerror-unsupported-operand-types-string-int-in

Full line from error log is:

```
[Mon Nov 22 22:22:11.603578 2021] [proxy_fcgi:error] [pid 11754] [client xxx] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "moduleList" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "moduleList" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "moduleList" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "moduleList" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "moduleList" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "moduleList" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "moduleList" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "moduleList" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "moduleList" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "moduleList" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "LBL_SEARCH_BUTTON" in /var/www/html/suitecrm/cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 662PHP message: PHP Warning:  Undefined array key "footer_buttons" in /var/www/html/suitecrm/cache/smarty/templates_c/%%BF^BF1^BF139AEF%%actions_buttons.tpl.php on line 28PHP message: PHP Warning:  Undefined array key "ADMIN_EDIT" in /var/www/html/suitecrm/cache/smarty/templates_c/%%41^41A^41AF2717%%header.tpl.php on line 106PHP message: PHP Warning:  Undefined array key "panelCount" in /var/www/html/suitecrm/cache/smarty/templates_c/%%41^41A^41AF2717%%header.tpl.php on line 108PHP message: PHP Warning:  Undefined array key "collapsed" in /var/www/html/suitecrm/cache/smarty/templates_c/%%07^072^072FA7F7%%EditView.tpl.php on line 244PHP message: PHP Warning:  Undefined array key "inline_edit" in /var/www/html/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php on line 108PHP message: PHP Warning:  Undefined array key "colspan" in /var/www/html/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php on line 110PHP message: PHP Warning:  Undefined array key "prefix" in /var/www/html/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php on line 139PHP message: PHP Warning:  Undefined array key "displayParams" in /var/www/html/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php on line 158PHP message: PHP Warning:  Undefined array key "ACCKEY" in /var/www/html/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php on line 160PHP message: PHP Warning:  Undefined array key "displayParams" in /var/www/html/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php on line 160PHP message: PHP Warning:  Undefined array key "type" in /var/www/html/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php on line 160PHP message: PHP Warning:  Undefined array key "help" in /var/www/html/suitecrm/cache/smarty/templates_c/%%62^62E^62E293EC%%EditView.tpl.php on line 64PHP message: PHP Warning:  Undefined array key "field" in /var/www/html/suitecrm/cache/smarty/templates_c/%%62^62E^62E293EC%%EditView.tpl.php on line 68PHP message: PHP Warning:  Undefined array key "inline_edit" in /var/www/html/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php on line 174PHP message: PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string % int in /var/www/html/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php:194\nStack trace:\n#0 /var/www/html/suitecrm/vendor/smarty/smarty/libs/Smarty.class.php(1875): include()\n#1 /var/www/html/suitecrm/include/Sugar_Smarty.php(168): Smarty->_smarty_include()\n#2 /var/www/html/suitecrm/cache/smarty/templates_c/%%07^072^072FA7F7%%EditView.tpl.php(260): Sugar_Smarty->_smarty_include()\n#3 /var/www/html/suitecrm/vendor/smarty/smarty/libs/Smarty.class.php(1269): include('...')\n#4 /var/www/html/suitecrm/include/Sugar_Smarty.php(151): Smarty->fetch()\n#5 /var/www/html/suitecrm/include/TemplateHandler/TemplateHandler.php(172): Sugar_Smarty->fetch()\n#6 /var/www/html/suitecrm/include/TemplateHandler/TemplateHandler.php(361): TemplateHandler->buildTemplate()\n#7 /var/www/html/suitecrm/include/EditView/EditView2.php(934): TemplateHandler->displayTemplate()\n#8 /var/www/html/suitecrm/include/MVC/View/vi...', referer: http://localhost/suitecrm/index.php?module=OAuth2Clients&action=index
```

#### Steps to Reproduce

Install server, no deviations from [docs](https://docs.suitecrm.com/admin/installation-guide/downloading-installing/). Go to Admin, 

OAuth2 Clients and Tokens, New Password Client. See gibberish.  

#### Context

Cant use nextcloud desktop plugin (primary reason I'm interested in suitecrm tbh)

#### Your Environment

* SuiteCRM Version used: 7.12.1
* Environment name and version:  MySQL, Apache2, PHP 8.0
* Operating System and version: Debian 10

**Comment by johnM2401** [comment]
Hey

Thank you for raising this issue!

I've given this a look, and I am able to replicate this using PHP 8.0
However, this does *not* appear to be an issue on 7.3 or 7.4

For now, you may be able to work around this by using PHP 7.3/7.4, (if that is an option for yourself)

Either way, I've marked this as a bug, thank you again for raising this!
