### ISSUE TITLE
Exception merging records - bean is bool in SugarRelationship

### ISSUE THREAD

**Issue by vladaman** [salesagility/SuiteCRM#9565]
Today we tried to merge a record and SuiteCRM thew an error. We identified following line where $bean variable is not an object but it's bool -> false

https://github.com/salesagility/SuiteCRM/blob/9cb957e4f41562eb44f6ce8c982e2a3c169fc951/data/Relationships/SugarRelationship.php#L476

SuiteCRM version 7.12.2

For internal use we changed it to following:
```php
foreach (self::$beansToResave as $module => $beans) {
   foreach ($beans as $bean) {
       if (is_bool($bean)){
                 // TODO should handle invalid state
       } else if (empty($bean->deleted) && empty($bean->in_save)) {
```

Exception:
```
PHP Fatal error:  Uncaught Error: Call to a member function save() on bool in /tmp/SuiteCRM-7.10.11/data/Relationships/SugarRelationship.php:477
Stack trace:
#0 /tmp/SuiteCRM-7.10.11/data/Relationships/One2MBeanRelationship.php(117): SugarRelationship::resaveRelatedBeans()
#1 /tmp/SuiteCRM-7.10.11/data/Link2.php(549): One2MBeanRelationship->add()
#2 /tmp/SuiteCRM-7.10.11/data/SugarBean.php(2996): Link2->add()
#3 /tmp/SuiteCRM-7.10.11/data/SugarBean.php(2723): SugarBean->update_parent_relationships()
#4 /tmp/SuiteCRM-7.10.11/data/SugarBean.php(2359): SugarBean->save_relationship_changes()
#5 /tmp/SuiteCRM-7.10.11/include/SugarObjects/templates/file/File.php(85): SugarBean->save()
#6 /tmp/SuiteCRM-7.10.11/modules/Notes/controller.php(95): File->save()
#7 /tmp/SuiteCRM-7.10.11/include/MVC/Controller/SugarController.php(522): NotesController->action_save()
#8 in /tmp/SuiteCRM-7.10.11/data/Relationships/SugarRelationship.php on line 477
```

**Comment by johnM2401** [comment]
Hey there

Could you give us some more information on this?

What PHP version are you using on this environment?
Which MYSQL/MariaDB version are you using for this environment?

In the module/records that you tried to merge, was there anything that's not out of the box?
(ie: On a Custom Module / Records contain Custom Fields / Records contain Custom Relationships / Custom Coded functionality on Module)

The Fatal Error does seem to specify a One to Many relationship, do you know what One-to-Many relationships this record has?
(And have you noticed any issues ON these related modules?)

Thanks!
John

**Comment by serhiisamko091184** [comment]
Hello, @vladaman 

The issue has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hey @vladaman 

Closing this issue due to inactivity. 
Thank you.

Regards,
Serhii
