### ISSUE TITLE
SuiteCRM 7.12.7 service/v3_1/SugarWebServiceImplv3_1.php PHP Fatal Error

### ISSUE THREAD

**Issue by Laurentzed** [salesagility/SuiteCRM#9749]
#### Issue

PHP Fatal error when importing emails from Implicit FrontEnd for SuiteCRM which prevents Outlook emails but also every other records to be pushed from Outlook to SuiteCRM server with release 7.12.7 whereas working with 7.12.5
#### Actual Behavior

Synchronization with Implicit FrontEnd from Outlook Emails/Contact/Accounts/Opportunities/Cases/Tasks  to SuiteCRM server.
Apache Log file shows:
     PHP Fatal error:  Uncaught Error: Using $this when not in object context in 
      /var/www/html/SuiteCRM/service/v3_1/SugarWebServiceImplv3_1.php:267

#### Possible Fix

Comment SugarWebServiceImplv3_1.php lines from 267 through 271 (lines reminded below from the orginal file).
        $valid = $this->validateFields($name_value_list, $module_name);
        if ($valid === false) {
            $GLOBALS['log']->info('End: SugarWebServiceImpl->set_entry');
            return;
        }

#### Steps to Reproduce

1. From Outlook archive an email to SuiteCRM server

#### Your Environment

* SuiteCRM Version used: 7.12.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Microsoft Edge Version 104.0.1293.70 (Official build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 10.3.34-MariaDB, PHP 7.4.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 20.04.5 LTS (up-to-date)

**Comment by pgorod** [comment]
It would be nice if you could get a stack trace of that FATAL error. This is being called from somewhere as a static method, it would help to know where from...

**Comment by pgorod** [comment]
Judging by the way the rest of the function uses to call the class methods, **`$this->validateFields`** probably needs to be changed to **`self::$helperObject->validateFields`**, but I didn't fully examine this, and I didn't test it, it's just a hunch.

**Comment by Laurentzed** [comment]
> It would be nice if you could get a stack trace of that FATAL error. This is being called from somewhere as a static method, it would help to know where from...

Here is the Apache log trace I have:
[Fri Sep 02 11:19:42.349961 2022] [php7:error] [pid 1431] [client 10.0.2.2:55681] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /var/www/html/SuiteCRM/service/v3_1/SugarWebServiceImplv3_1.php:267\nStack trace:\n#0 /var/www/html/SuiteCRM/include/nusoap/nusoap.php(5437): SugarWebServiceImplv3_1::set_entry()\n#1 /var/www/html/SuiteCRM/include/nusoap/nusoap.php(5054): nusoap_server->invoke_method()\n#2 /var/www/html/SuiteCRM/service/core/NusoapSoap.php(93): nusoap_server->service()\n#3 /var/www/html/SuiteCRM/service/core/webservice.php(70): NusoapSoap->serve()\n#4 /var/www/html/SuiteCRM/service/v4_1/soap.php(56): require_once('/var/www/html/S...')\n#5 {main}\n  thrown in /var/www/html/SuiteCRM/service/v3_1/SugarWebServiceImplv3_1.php on line 267 

Is it the stack trace you asked for?

**Comment by pgorod** [comment]
Yes. Thanks. If you get a chance please test the change I proposed above...

**Comment by ebogaard** [comment]
We fixed this issue (introduced in 7.12.5) by changing the following files:
\# service/v3_1/SugarWebServiceImplv3_1.php : around row 267
```
        //$valid = $this->validateFields($name_value_list, $module_name);
        $valid = self::$helperObject->validateFields($name_value_list, $module_name);
```

The copying the following functions from "service/v3_1/SugarWebServiceImplv3_1.php" to "service/v4/SugarWebServiceUtilv4.php" in the "SugarWebServiceUtilv4" class.
* validateFields => make this one public
* isIdField
* validateId

**Comment by bunglex** [comment]
Many thanks, this solved a problem for me using 7.13.1

I was getting fatal errors when trying to create a new contact via SOAP set_entity.

**Comment by chris001** [comment]
@ebogaard Can you make a PR with your code fix?
