### ISSUE TITLE
Since version 7.12.5 an email import is no longer possible 

### ISSUE THREAD

**Issue by C42AT** [salesagility/SuiteCRM#9807]
#### Issue

Since version 7.12.5 an email import is no longer possible

#### Expected Behavior

Since version 7.12.5 an email import is no longer possible  -> Modal "An error has occurred"

-> http://xxxxxxx/index.php?module=Emails&action=ImportView&_=1666952964408 -> HTTP 500 Response

#### Actual Behavior

PHP Error-LOG:

`Fatal error: Uncaught TypeError: Unsupported operand types: string % int in /bitnami/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php:194 Stack trace: #0 /bitnami/suitecrm/vendor/smarty/smarty/libs/Smarty.class.php(1875): include() #1 /bitnami/suitecrm/include/Sugar_Smarty.php(168): Smarty->_smarty_include() #2 /bitnami/suitecrm/cache/smarty/templates_c/%%A2^A25^A25BDAE8%%ImportView.tpl.php(156): Sugar_Smarty->_smarty_include() #3 /bitnami/suitecrm/vendor/smarty/smarty/libs/Smarty.class.php(1269): include('...') #4 /bitnami/suitecrm/include/Sugar_Smarty.php(151): Smarty->fetch() #5 /bitnami/suitecrm/include/TemplateHandler/TemplateHandler.php(172): Sugar_Smarty->fetch() #6 /bitnami/suitecrm/include/TemplateHandler/TemplateHandler.php(361): TemplateHandler->buildTemplate() #7 /bitnami/suitecrm/include/EditView/EditView2.php(934): TemplateHandler->displayTemplate() #8 /bitnami/suitecrm/include/MVC/View/views/view.edit.php(104): EditView->display() #9 /bitnami/suitecrm/include/MVC/View/SugarView.php(210): ViewEdit->display() #10 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(432): SugarView->process() #11 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(363): SugarController->processView() #12 /bitnami/suitecrm/include/MVC/SugarApplication.php(101): SugarController->execute() #13 /bitnami/suitecrm/index.php(55): SugarApplication->execute() #14 {main} thrown in /bitnami/suitecrm/cache/smarty/templates_c/%%1A^1AB^1AB6DD00%%tab_panel_content.tpl.php on line 194`

#### Steps to Reproduce
1. Menu -> Email (IMAP)
2. Mark or Open Email
3. Bulk Action or Single Action: IMPORT

-> Broswer Console:  sugar_grp1_jquery.js?v=cKF5_SXiQ85BhW-fTYRB9A:2          GET http://xxxxx/index.php?module=Emails&action=ImportView&_=1666952964408 500 (Internal Server Error)

#### Context

High priority: A corresponding allocation of the emails in SuiteCRM is therefore not possible, so that consistent documentation can no longer be guaranteed - the CRM system becomes unusable.

#### Your Environment
* SuiteCRM Version used: 7.12.4/5/6/7
* Browser Googel Chrome: Version 106.0.5249.119, Firefox 106.0.2 
-   "smarty/smarty": "^2.6",
- PHP Version 8.0.20, Apache,
- MariaDB 10.5

**Comment by C42AT** [comment]
Now I was able to further isolate the problem:

modules/Emails/include/ImportView/ImportView.tpl Line: 120
`{{include file='themes/SuiteP/include/EditView/tab_panel_content.tpl'}}`

-> themes/SuiteP/include/EditView/tab_panel_content.tpl Line: 140

```                
{{if $col%2==1}}
                <div class="clear"></div>
                {{/if}}
```
Error: 
Fatal error: Uncaught TypeError: Unsupported operand types: string % int in 

This could be the solution: convert $col to int from **$col%2** to **$col|intval%2**

```
                {{if $col|intval%2==1}}
                <div class="clear"></div>
                {{/if}}
```

**Comment by alvanson** [comment]
Confirmed that @C42AT's proposed solution solved the issue for me - SuiteCRM 7.13.1, PHP 8.0.27.
