### ISSUE TITLE
Elasticsearch failing to index cases

### ISSUE THREAD

**Issue by cyb456** [salesagility/SuiteCRM#9990]
#### Issue

I have a relate field to a custom module made in studio. This is stored in cases_cstm.mymodule_id_c

I get this error when trying to do a full index. After examing the query in suitecrm.log the join table is missing the cases_cstm join. After manually changing the query in phpmyadmin to join cases_cstm the query does not error.

```
[@][12:07:35] Indexing module Cases...
[@][12:07:38] Indexed 1000
Database failure. Please refer to suitecrm.log for details.[!][12:07:38] Failed to index module Cases! Exception details follow
[!][12:07:38] Exception: Database failure. Please refer to suitecrm.log for details. in [site]/include/utils.php:1987
  ~  ~  ~  ~  Stack trace:
  ~  ~  ~  ~  #0 [site]/include/database/DBManager.php(353): sugar_die()
  ~  ~  ~  ~  #1 [site]/include/database/DBManager.php(328): DBManager->registerError()
  ~  ~  ~  ~  #2 [site]/include/database/MysqliManager.php(179): DBManager->checkError()
  ~  ~  ~  ~  #3 [site]/include/database/MysqlManager.php(285): MysqliManager->query()
  ~  ~  ~  ~  #4 [site]/data/SugarBean.php(4280): MysqlManager->limitQuery()
  ~  ~  ~  ~  #5 [site]/data/SugarBean.php(3526): SugarBean->process_list_query()
  ~  ~  ~  ~  #6 [site]/lib/Search/ElasticSearch/ElasticSearchModuleDataPuller.php(167): SugarBean->get_list()
  ~  ~  ~  ~  #7 [site]/lib/Search/ElasticSearch/ElasticSearchIndexer.php(212): SuiteCRM\Search\ElasticSearch\ElasticSearchModuleDataPuller->pullNextBatch()
  ~  ~  ~  ~  #8 [site]/lib/Search/ElasticSearch/ElasticSearchIndexer.php(146): SuiteCRM\Search\ElasticSearch\ElasticSearchIndexer->indexModule()
  ~  ~  ~  ~  #9 [site]/lib/Search/ElasticSearch/ElasticSearchIndexer.php(588): SuiteCRM\Search\ElasticSearch\ElasticSearchIndexer->index()
  ~  ~  ~  ~  #10 [site]/lib/Robo/Plugin/Commands/ElasticSearchCommands.php(120): SuiteCRM\Search\ElasticSearch\ElasticSearchIndexer::repairElasticsearchIndex()
  ~  ~  ~  ~  #11 [internal function]: SuiteCRM\Robo\Plugin\Commands\ElasticSearchCommands->elasticIndex()
  ~  ~  ~  ~  #12 [site]/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array()
  ~  ~  ~  ~  #13 [site]/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
  ~  ~  ~  ~  #14 [site]/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
  ~  ~  ~  ~  #15 [site]/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process()
  ~  ~  ~  ~  #16 [site]/vendor/symfony/console/Command/Command.php(298): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
  ~  ~  ~  ~  #17 [site]/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run()
  ~  ~  ~  ~  #18 [site]/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
  ~  ~  ~  ~  #19 [site]/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
  ~  ~  ~  ~  #20 [site]/vendor/consolidation/robo/src/Runner.php(282): Symfony\Component\Console\Application->run()
  ~  ~  ~  ~  #21 [site]/vendor/consolidation/robo/src/Runner.php(158): Robo\Runner->run()
  ~  ~  ~  ~  #22 [site]/vendor/consolidation/robo/robo(48): Robo\Runner->execute()
  ~  ~  ~  ~  #23 [site]/vendor/bin/robo(115): include('/var/www/...')
  ~  ~  ~  ~  #24 {main}
[@][12:07:38] Indexing module Accounts...
```
#### Expected Behavior

no error
#### Actual Behavior

error
#### Possible Fix

detailed above
#### Steps to Reproduce

1. add a one way relate field to cases
2. try to do an elasticsearch robo index
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.13.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chromium
* Environment name and version (e.g. MySQL, PHP 7): php 7.4 mariadb
* Operating System and version (e.g Ubuntu 16.04): ubuntu 20.04

**Comment by cyb456** [comment]
I was able to hacky fix it by adding 
if($this->object_name == 'Case'){ return true; }
to SugarBean.php in hasCustomFields()

For some reason hasCustomFields() is blank/false for Cases when running the elasticsearch index

**Comment by cyb456** [comment]
I am again asking if someone could look into this, still occuring after pulling in the changes from https://github.com/salesagility/SuiteCRM/pull/10275

the root issue is $GLOBALS['dictionary']['Case']['custom_fields'] seems to always be false when run from robo or cron(command line)

So if I have custom field in my cases module, it breaks the indexing.

**Comment by chris001** [comment]
@JanSiero  Any suggestions?

**Comment by pgorod** [comment]
Can anyone get a stack trace at that point (function hasCustomFields), when running from the Scheduler or cron (the cases where it fails)? Knowing where it is being called from would likely provide clues about why it's failing.

Maybe it's as simple as ensuring there is an instantiation of the global variables before accessing them.

**Comment by cyb456** [comment]
> Can anyone get a stack trace at that point (function hasCustomFields), when running from the Scheduler or cron (the cases where it fails)? Knowing where it is being called from would likely provide clues about why it's failing.
> 
> Maybe it's as simple as ensuring there is an instantiation of the global variables before accessing them.

There are multiple places within the generate list query method where it checks that to make the query, what I essentially did to patch it for myself was replace

```if ($temp->hasCustomFields())```

with 

```if ($temp->hasCustomFields() || $temp->object_name == "Case")```

wherever I saw it, obviously this is not a real solution

**Comment by cyb456** [comment]
one other thing I noticed is LIMIT 1000, 1000, does that mean the first 0-1000 worked?

**Comment by cyb456** [comment]
> `LIMIT` is not compatible with Microsoft SQL Server or standard SQL, so it should be changed to be compatible with the standard SQL. For example:
> 
> https://github.com/salesagility/SuiteCRM/blob/b39d9610f705807ce4b595c04031b001c2f0c819/include/database/MssqlManager.php#L433

That should probably be in a new issue then

**Comment by chris001** [comment]
Done! Issue #10350
