### ISSUE TITLE
Elasticsearch fails to index inline edit checkbox

### ISSUE THREAD

**Issue by cyb456** [salesagility/SuiteCRM#9992]
#### Issue

Inline edit a checkbox and this showed up in the logs and the record name did not show up on search results
```
Fri Mar 17 17:15:23 2023 [1119846][78feb03b-73b8-f12a-16ab-63925fb72b82][ERROR] [ElasticSearchIndexer] Failed to index bean to index
Fri Mar 17 17:15:23 2023 [1119846][78feb03b-73b8-f12a-16ab-63925fb72b82][ERROR] [ElasticSearchIndexer] Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse field [consult_training_hours] of type [boolean] in document with id 'acc0f25f-75ab-c31f-02eb-6414d810ff90'. Preview of field's value: '0'"}],"type":"mapper_parsing_exception","reason":"failed to parse field [consult_training_hours] of type [boolean] in document with id 'acc0f25f-75ab-c31f-02eb-6414d810ff90'. Preview of field's value: '0'","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [0] as only [true] or [false] are allowed."}},"status":400} in [site]/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:693
Stack trace:
#0 [site]/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(333): Elasticsearch\Connections\Connection->process4xxError()
#1 [site]/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#2 [site]/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(65): React\Promise\FulfilledPromise->then()
#3 [site]/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then()
#4 [site]/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(345): GuzzleHttp\Ring\Core::proxy()
#5 [site]/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(241): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#6 [site]/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\Connections\Connection->performRequest()
#7 [site]/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1929): Elasticsearch\Transport->performRequest()
#8 [site]/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(911): Elasticsearch\Client->performRequest()
#9 [site]/lib/Search/ElasticSearch/ElasticSearchIndexer.php(294): Elasticsearch\Client->index()
#10 [site]/lib/Search/ElasticSearch/ElasticSearchHooks.php(181): SuiteCRM\Search\ElasticSearch\ElasticSearchIndexer->indexBean()
#11 [site]/lib/Search/ElasticSearch/ElasticSearchHooks.php(137): SuiteCRM\Search\ElasticSearch\ElasticSearchHooks->performAction()
#12 [site]/lib/Search/ElasticSearch/ElasticSearchHooks.php(107): SuiteCRM\Search\ElasticSearch\ElasticSearchHooks->reIndex()
#13 [site]/lib/Search/ElasticSearch/ElasticSearchHooks.php(77): SuiteCRM\Search\ElasticSearch\ElasticSearchHooks->reIndexSafe()
#14 [site]/include/utils/LogicHook.php(260): SuiteCRM\Search\ElasticSearch\ElasticSearchHooks->beanSaved()
#15 [site]/include/utils/LogicHook.php(201): LogicHook->process_hooks()
#16 [site]/data/SugarBean.php(3179): LogicHook->call_custom_logic()
#17 [site]/data/SugarBean.php(2426): SugarBean->call_custom_logic()
#18 [site]/include/InlineEditing/InlineEditing.php(381): SugarBean->save()
#19 [site]/modules/Home/controller.php(60): saveField()
#20 [site]/include/MVC/Controller/SugarController.php(522): HomeController->action_saveHTMLField()
#21 [site]/include/MVC/Controller/SugarController.php(491): SugarController->do_action()
#22 [site]/include/MVC/Controller/SugarController.php(465): SugarController->handle_action()
#23 [site]/include/MVC/Controller/SugarController.php(361): SugarController->process()
#24 [site]/include/MVC/SugarApplication.php(101): SugarController->execute()
#25 [site]/index.php(52): SugarApplication->execute()
#26 {main}
```
#### Expected Behavior

indexing should work properly
#### Actual Behavior

it does not index and gives this error
#### Steps to Reproduce

1. inline edit a checkbox
2. make change to record name
3. search new record name
4. no results

#### Your Environment

* SuiteCRM Version used: 7.13.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome
* Environment name and version (e.g. MySQL, PHP 7): php 7.4, mariadb
* Operating System and version (e.g Ubuntu 16.04): ubuntu 20.04

**Comment by johnM2401** [comment]
Hey!

Thanks for getting in touch with your issues

I've been trying to replicate this, but have had no luck i'm afraid.

Would you know what Elasticsearch version you are experiencing this on, by chance?

I'm trying on 7.9.3 and boolean-type fields appear to index well:

![bool](https://github.com/salesagility/SuiteCRM/assets/13675281/bec74052-4cb7-4205-93ea-1e96ebf597d7)

Perhaps I have missed something?


Would you have any further information?
Thanks!

**Comment by cyb456** [comment]
closing this no longer relevant
